teralizer {
  project {
    root-path = "data/jarvis-census/fixtures/commons-math-3.5-census"
    use-test-generation = false
    use-test-generalization = true
  }

  jpf {
    max-execution-time = 30
    max-path-condition-size = 100000
  }

  junit {
    max-execution-time = 120
  }

  pitest {
    mutators = "DEFAULTS"
    max-execution-time = 300
  }

  generalizations {
    NAIVE_100_TRIES {
      algorithm = "NAIVE"
      jqwik { tries = 100 }
    }
    IMPROVED_100_TRIES {
      algorithm = "IMPROVED"
      jqwik { tries = 100 }
    }
  }
}
