teralizer {
  project {
    root-path = "data/jarvis-census/fixtures/commons-jexl-3.0-census"
    use-test-generation = false
    use-test-generalization = true
  }

  jpf {
    max-path-condition-size = 100000
  }

  pitest {
    mutators = "DEFAULTS"
  }

  generalizations {
    IMPROVED_100_TRIES {
      algorithm = "IMPROVED"
      jqwik { tries = 100 }
    }
  }
}
