/* This file was automatically generated by EvoSuite
Sun Apr 13 12:07:49 GMT 2025
 */
package org.apache.commons.collections4.bloomfilter;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
import org.apache.commons.collections4.bloomfilter.BitMaps;
public class BitMaps_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        long[] longArray0 = org.apache.commons.collections4.bloomfilter.BitMaps.newBitMap(2162);
        org.apache.commons.collections4.bloomfilter.BitMaps.set(longArray0, 0);
        org.apache.commons.collections4.bloomfilter.BitMaps.set(longArray0, 0);
        org.junit.jupiter.api.Assertions.assertEquals(34, longArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test01() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.numberOfBitMaps(0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.numberOfBitMaps(819);
        org.junit.jupiter.api.Assertions.assertEquals(13, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.mod(63L, 63);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.mod(-1269L, -2137159206);
        org.junit.jupiter.api.Assertions.assertEquals(-1831916139, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.getLongIndex(1522);
        org.junit.jupiter.api.Assertions.assertEquals(23, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.getLongIndex(-1831916139);
        org.junit.jupiter.api.Assertions.assertEquals(-28623690, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        long long0 = org.apache.commons.collections4.bloomfilter.BitMaps.getLongBit(-1);
        org.junit.jupiter.api.Assertions.assertEquals(-9223372036854775808L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test14() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.getLongIndex(0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test15() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.numberOfBitMaps(-1244);
        org.junit.jupiter.api.Assertions.assertEquals(-19, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test16() throws java.lang.Throwable {
        long long0 = org.apache.commons.collections4.bloomfilter.BitMaps.getLongBit(23);
        org.junit.jupiter.api.Assertions.assertEquals(8388608L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test17() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.mod(413, -1);
        org.junit.jupiter.api.Assertions.assertEquals(2, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test18() throws java.lang.Throwable {
        int int0 = org.apache.commons.collections4.bloomfilter.BitMaps.mod(1330L, 162);
        org.junit.jupiter.api.Assertions.assertEquals(34, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test19() throws java.lang.Throwable {
        long[] longArray0 = new long[7];
        longArray0[6] = ((long) (-1));
        boolean boolean0 = org.apache.commons.collections4.bloomfilter.BitMaps.contains(longArray0, 447);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test20() throws java.lang.Throwable {
        long[] longArray0 = new long[8];
        org.apache.commons.collections4.bloomfilter.BitMaps.set(longArray0, 0);
        boolean boolean0 = org.apache.commons.collections4.bloomfilter.BitMaps.contains(longArray0, 0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new long[]{ 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L }, longArray0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test21() throws java.lang.Throwable {
        long[] longArray0 = new long[7];
        boolean boolean0 = org.apache.commons.collections4.bloomfilter.BitMaps.contains(longArray0, 447);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }
}