package teralizer.processing;

public enum ProcessingStage {
    CLEANUP_PROJECT(0),

    DOWNLOAD_PROJECT(1),
    SETUP_PROJECT(2),

    BUILD_PROJECT_ORIGINAL(3),
    GENERATE_EVOSUITE_TESTS(4),
    POSTPROCESS_EVOSUITE_TESTS(5),

    BUILD_SPOON_MODEL(6),

    EXECUTE_TESTS_ORIGINAL(7),
    COLLECT_JUNIT_REPORTS_ORIGINAL(8),
    ANALYZE_TESTS(9),
    FILTER_TESTS(10),
    FILTER_ASSERTIONS(11),

    ADD_JPF_INSTRUMENTATION(12),
    BUILD_PROJECT_INSTRUMENTED(13),
    EXECUTE_JPF(14),
    ANALYZE_JPF(15),
    CLEANUP_JPF_INSTRUMENTATION(16),

    ADD_DEPENDENCIES(17),
    BUILD_PROJECT_INITIAL(18),
    EXECUTE_TESTS_INITIAL(19),

    COLLECT_JUNIT_REPORTS_INITIAL(20),
    COLLECT_JACOCO_DATA_INITIAL(21),
    COLLECT_PIT_DATA_INITIAL(22),

    CLEANUP_GENERALIZATION(23),

    GENERALIZE_TESTS(24),
    BUILD_PROJECT_GENERALIZED(25),

    EXECUTE_TESTS_GENERALIZED(26),
    COLLECT_JUNIT_REPORTS_GENERALIZED(27),
    FILTER_GENERALIZATIONS(28),

    COLLECT_JACOCO_DATA_GENERALIZED(29),
    COLLECT_PIT_DATA_GENERALIZED(30);

    private final Integer step;

    ProcessingStage(Integer step) {
        this.step = step;
    }

    public Integer getStep() {
        return this.step;
    }
}
