package teralizer.processing;

public enum ProcessingStage {
    CLEANUP(null),

    PROJECT_DOWNLOAD(1),
    PROJECT_SETUP(2),
    PROJECT_BUILDING_ORIGINAL(3),
    TEST_EXECUTION_ORIGINAL(4),

    ADD_DEPENDENCIES(5),
    PROJECT_BUILDING_WITH_DEPENDENCIES(6),
    TEST_EXECUTION_WITH_DEPENDENCIES(7),

    TEST_DETECTION(8),
    TEST_FILTERING(9),

    TEST_DATA_COLLECTION_ORIGINAL(10),
    MUTATION_DATA_COLLECTION_ORIGINAL(11),

    JPF_INSTRUMENTATION(12),
    PROJECT_BUILDING_INSTRUMENTED(13),
    JPF_EXECUTION(14),

    TEST_GENERALIZATION(15),
    PROJECT_BUILDING_GENERALIZED(16),
    TEST_EXECUTION_GENERALIZED(17),

    TEST_DATA_COLLECTION_GENERALIZED(18),
    MUTATION_DATA_COLLECTION_GENERALIZED(19);

    private final Integer step;

    ProcessingStage(Integer step) {
        this.step = step;
    }

    public Integer getStep() {
        return this.step;
    }
}
