package teralizer.processing;

public enum ProcessingStage {
    CLEANUP_PROJECT(0),

    DOWNLOAD_PROJECT(1),
    SETUP_PROJECT(2),

    ADD_DEPENDENCIES(3),
    BUILD_PROJECT_ORIGINAL(4),

    GENERATE_EVOSUITE_TESTS(5),
    POSTPROCESS_EVOSUITE_TESTS(6),

    BUILD_SPOON_MODEL(7),

    EXECUTE_TESTS_ORIGINAL(8),
    COLLECT_JUNIT_REPORTS_ORIGINAL(9),
    COLLECT_JACOCO_DATA_ORIGINAL(10),
    FILTER_TESTS_ORIGINAL(11),

    ANALYZE_TESTS(12),
    FILTER_TESTS(13),
    FILTER_ASSERTIONS(14),

    ADD_JPF_INSTRUMENTATION(15),
    BUILD_PROJECT_INSTRUMENTED(16),
    EXECUTE_JPF(17),
    ANALYZE_JPF(18),
    CLEANUP_JPF_INSTRUMENTATION(19),

    BUILD_PROJECT_INITIAL(20),
    EXECUTE_TESTS_INITIAL(21),

    COLLECT_JUNIT_REPORTS_INITIAL(22),

    CLEANUP_GENERALIZATION(23),

    GENERALIZE_TESTS(24),
    BUILD_PROJECT_GENERALIZED(25),

    EXECUTE_TESTS_GENERALIZED(26),
    COLLECT_JUNIT_REPORTS_GENERALIZED(27),
    FILTER_GENERALIZATIONS(28),

    COLLECT_PIT_DATA_ORIGINAL(29),
    COLLECT_JACOCO_DATA_INITIAL(30),
    COLLECT_PIT_DATA_INITIAL(31),
    RESTORE_GENERALIZED_BUILD(32),
    COLLECT_JACOCO_DATA_GENERALIZED(33),
    COLLECT_PIT_DATA_GENERALIZED(34);

    private final Integer step;

    ProcessingStage(Integer step) {
        this.step = step;
    }

    public Integer getStep() {
        return this.step;
    }
}
