/* This file was automatically generated by EvoSuite
Fri Apr 04 14:08:41 GMT 2025
 */
package org.apache.commons.numbers.gamma;
import org.apache.commons.numbers.angle.Angle;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import java.util.function.DoubleSupplier;
import static org.junit.jupiter.api.Assertions.*;
import org.apache.commons.numbers.core.Sum;
import java.util.concurrent.TimeUnit;
import org.apache.commons.numbers.gamma.BoostTools;
public class BoostTools_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Deg angle_Deg0 = Angle.Deg.ZERO;
        double double0 = org.apache.commons.numbers.gamma.BoostTools.sumSeries(angle_Deg0, 0.0, 1073731856, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Turn angle_Turn0 = Angle.Turn.ZERO;
        org.apache.commons.numbers.angle.Angle.Rad angle_Rad0 = angle_Turn0.toRad();
        double double0 = org.apache.commons.numbers.gamma.BoostTools.sumSeries(angle_Rad0, 6.283185307179586, 1659, 6.283185307179586);
        org.junit.jupiter.api.Assertions.assertEquals(6.283185307179586, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Turn angle_Turn0 = Angle.Turn.ZERO;
        org.apache.commons.numbers.angle.Angle.Rad angle_Rad0 = angle_Turn0.toRad();
        double double0 = org.apache.commons.numbers.gamma.BoostTools.sumSeries(angle_Rad0, 1172.712137, 2, -2249.3);
        org.junit.jupiter.api.Assertions.assertEquals(-2249.3, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Rad angle_Rad0 = Angle.Rad.PI;
        double double0 = org.apache.commons.numbers.gamma.BoostTools.sumSeries(angle_Rad0, 0.008627862153610836, 1585);
        org.junit.jupiter.api.Assertions.assertEquals(364.42474781641533, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Deg angle_Deg0 = Angle.Deg.of(-2125.8);
        org.apache.commons.numbers.angle.Angle.Turn angle_Turn0 = angle_Deg0.toTurn();
        double double0 = org.apache.commons.numbers.gamma.BoostTools.sumSeries(angle_Turn0, 1943.07014322, 12);
        org.junit.jupiter.api.Assertions.assertEquals(-5.905, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Turn angle_Turn0 = Angle.Turn.of(0.0);
        org.apache.commons.numbers.angle.Angle.Deg angle_Deg0 = angle_Turn0.toDeg();
        double double0 = org.apache.commons.numbers.gamma.BoostTools.kahanSumSeries(angle_Deg0, 2.220446049250313E-16, 551, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Deg angle_Deg0 = Angle.Deg.of(512.18);
        double double0 = org.apache.commons.numbers.gamma.BoostTools.kahanSumSeries(angle_Deg0, 1.5707963267948966, 979, 1.5707963267948966);
        org.junit.jupiter.api.Assertions.assertEquals(513.7507963267949, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test09() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Deg angle_Deg0 = Angle.Deg.of(-1.0);
        double double0 = org.apache.commons.numbers.gamma.BoostTools.kahanSumSeries(angle_Deg0, 6.283185307179586, 610, 1.0);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test10() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Turn angle_Turn0 = Angle.Turn.ZERO;
        double double0 = org.apache.commons.numbers.gamma.BoostTools.kahanSumSeries(angle_Turn0, -1.0, 2332);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test11() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Deg angle_Deg0 = Angle.Deg.of(840.9056732340875);
        double double0 = org.apache.commons.numbers.gamma.BoostTools.kahanSumSeries(angle_Deg0, 1.5707963267948966, 2);
        org.junit.jupiter.api.Assertions.assertEquals(840.9056732340875, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        double[] doubleArray0 = new double[9];
        doubleArray0[1] = 2102.4865539908833;
        double double0 = org.apache.commons.numbers.gamma.BoostTools.evaluatePolynomial(doubleArray0, 3.141592653589793);
        org.junit.jupiter.api.Assertions.assertEquals(6605.156312289079, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test13() throws java.lang.Throwable {
        double[] doubleArray0 = new double[4];
        doubleArray0[1] = 1.5707963267948966;
        double double0 = org.apache.commons.numbers.gamma.BoostTools.evaluatePolynomial(doubleArray0, -2249.3);
        org.junit.jupiter.api.Assertions.assertEquals(-3533.192177859761, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test24() throws java.lang.Throwable {
        double[] doubleArray0 = new double[4];
        double double0 = org.apache.commons.numbers.gamma.BoostTools.evaluatePolynomial(doubleArray0, -2249.3);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test27() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Sum sum0 = org.apache.commons.numbers.core.Sum.create();
        double double0 = org.apache.commons.numbers.gamma.BoostTools.sumSeries(sum0, 0.0, 2);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test28() throws java.lang.Throwable {
        org.apache.commons.numbers.angle.Angle.Rad angle_Rad0 = Angle.Rad.of(-2495.444);
        org.apache.commons.numbers.angle.Angle.Deg angle_Deg0 = angle_Rad0.toDeg();
        org.apache.commons.numbers.angle.Angle.Turn angle_Turn0 = angle_Deg0.toTurn();
        double double0 = org.apache.commons.numbers.gamma.BoostTools.kahanSumSeries(angle_Turn0, 924.0036588, 17);
        org.junit.jupiter.api.Assertions.assertEquals(-397.16224780901166, double0, 0.01);
    }
}