/* This file was automatically generated by EvoSuite
Fri Apr 04 13:58:16 GMT 2025
 */
package org.apache.commons.numbers.gamma;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.apache.commons.numbers.gamma.Digamma;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
public class Digamma_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test0() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.Digamma.value(1.0E-5);
        org.junit.jupiter.api.Assertions.assertEquals(-100000.57721566489, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test1() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.Digamma.value(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test2() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.Digamma.value(-422.7500719095);
        org.junit.jupiter.api.Assertions.assertEquals(2.90495101251759, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test3() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.Digamma.value(java.lang.Double.NEGATIVE_INFINITY);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }
}