teralizer {
  project {
    root-path = "projects/EqBench"
    main-source-path = "projects/EqBench/src/main/code"
    test-source-path = "projects/EqBench/src/test/code"
    main-compiled-path = "projects/EqBench/target/classes"
    test-compiled-path = "projects/EqBench/target/test-classes"
    test-reports-path = "projects/EqBench/target/surefire-reports"
    coverage-reports-path = "projects/EqBench/target/site/jacoco"
    mutation-reports-path = "projects/EqBench/target/pit-reports"
  }
}
