services:
  teralizer:
    build: .
    environment:
      PROJECT_CONFIG_PATH: "project-configs/example-maven-junit5.conf"
    ports:
      - "8000:8000"
    volumes:
      - ./docker-data/database:/app/database
      - ./docker-data/data:/app/data
  adminer:
    image: adminer
    ports:
      - "18080:8080"
    volumes:
      - ./docker-data/database:/app/database
      - ./docker/adminer/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
