/* This file was automatically generated by EvoSuite
Thu Apr 03 21:55:29 GMT 2025
 */
package org.apache.commons.codec.binary;
import org.apache.commons.codec.binary.CharSequenceUtils;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.CharBuffer;
import java.util.concurrent.TimeUnit;
public class CharSequenceUtils_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        char[] charArray0 = new char[5];
        charArray0[0] = 'I';
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, true, 0, charBuffer0, 1, 'I');
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(((java.lang.CharSequence) (null)), true, -17, ((java.lang.CharSequence) (null)), -17, -17);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches("z-", false, 180, "", -1305, 0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        char[] charArray0 = new char[2];
        charArray0[0] = 's';
        charArray0[1] = 'S';
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, true, 1, charBuffer0, 0, 1);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        char[] charArray0 = new char[21];
        charArray0[0] = 'R';
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, false, 1, charBuffer0, '\u0000', 1);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        char[] charArray0 = new char[14];
        charArray0[0] = 'R';
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, true, 1, charBuffer0, '\u0000', 1);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test10() throws java.lang.Throwable {
        org.apache.commons.codec.binary.CharSequenceUtils charSequenceUtils0 = new org.apache.commons.codec.binary.CharSequenceUtils();
    }
}