teralizer {
  project {
    use-test-generation = false
    use-test-generalization = true
  }

  evosuite {
    stopping-condition = "MAXTIME"
    search-budget = "60"
    assertion-strategy = "MUTATION"
    coverage-criterion = "LINE:BRANCH:EXCEPTION:WEAKMUTATION:OUTPUT:METHOD:METHODNOEXCEPTION:CBRANCH"
  }

  jpf {
    max-execution-time = 10
    max-path-condition-size = 100000
  }

  junit {
    max-execution-time = 60
  }

  pitest {
    mutators = "DEFAULTS"
    max-execution-time = 60
  }

  generalizations {
    BASELINE {
      algorithm = "BASELINE"
      jqwik { tries = 1 }
    }
    NAIVE {
      algorithm = "NAIVE"
      jqwik { tries = 20 }
    }
    IMPROVED {
      algorithm = "IMPROVED"
      jqwik { tries = 20 }
    }
  }
}
