teralizer {
  project {
    use-test-generation = false
    use-test-generalization = true
  }

  evosuite {
    stopping-condition = "MAXTIME"
    search-budget = "60"
    assertion-strategy = "MUTATION"
    coverage-criterion = "LINE:BRANCH:EXCEPTION:WEAKMUTATION:OUTPUT:METHOD:METHODNOEXCEPTION:CBRANCH"
  }

  jpf {
    max-execution-time = 10
    max-path-condition-size = 1000000
    max-pc-overhead-percent = 20
  }

  pitest {
    mutators = "DEFAULTS"
  }
}
