/* This file was automatically generated by EvoSuite
Wed Mar 19 01:41:45 GMT 2025
 */
package org.apache.commons.compress.archivers.zip;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.apache.commons.compress.archivers.zip.ZipUtil;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.math.BigInteger;
import java.util.concurrent.TimeUnit;
public class ZipUtil_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        byte byte0 = org.apache.commons.compress.archivers.zip.ZipUtil.unsignedIntToSignedByte(0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), byte0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test01() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.toLong(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[3];
        byteArray0[0] = ((byte) (-67));
        java.math.BigInteger bigInteger0 = new java.math.BigInteger(byteArray0);
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.toLong(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(-4390912L, long0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigInteger0.byteValue());
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (-67)), ((byte) (0)), ((byte) (0)) }, byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(3, byteArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        int int0 = org.apache.commons.compress.archivers.zip.ZipUtil.signedByteToUnsignedInt(((byte) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[0];
        byte[] byteArray1 = org.apache.commons.compress.archivers.zip.ZipUtil.reverse(byteArray0);
        org.junit.jupiter.api.Assertions.assertSame(byteArray0, byteArray1);
        org.junit.jupiter.api.Assertions.assertSame(byteArray1, byteArray0);
        org.junit.jupiter.api.Assertions.assertNotNull(byteArray1);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{  }, byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{  }, byteArray1);
        org.junit.jupiter.api.Assertions.assertEquals(0, byteArray0.length);
        org.junit.jupiter.api.Assertions.assertEquals(0, byteArray1.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = org.apache.commons.compress.archivers.zip.ZipUtil.longToBig(-3533L);
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-3533)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (51)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.adjustToLong(0);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.adjustToLong(-1925);
        org.junit.jupiter.api.Assertions.assertEquals(4294965371L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test13() throws java.lang.Throwable {
        byte byte0 = org.apache.commons.compress.archivers.zip.ZipUtil.unsignedIntToSignedByte(165);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-91)), byte0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test15() throws java.lang.Throwable {
        byte byte0 = org.apache.commons.compress.archivers.zip.ZipUtil.unsignedIntToSignedByte(21);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (21)), byte0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test17() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[2];
        byte[] byteArray1 = org.apache.commons.compress.archivers.zip.ZipUtil.reverse(byteArray0);
        org.junit.jupiter.api.Assertions.assertSame(byteArray0, byteArray1);
        org.junit.jupiter.api.Assertions.assertSame(byteArray1, byteArray0);
        org.junit.jupiter.api.Assertions.assertNotNull(byteArray1);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (0)), ((byte) (0)) }, byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (0)), ((byte) (0)) }, byteArray1);
        org.junit.jupiter.api.Assertions.assertEquals(2, byteArray0.length);
        org.junit.jupiter.api.Assertions.assertEquals(2, byteArray1.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test19() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.compress.archivers.zip.ZipUtil.isDosTime(4036608000000L);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test20() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.compress.archivers.zip.ZipUtil.isDosTime(1392409281320L);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test21() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.compress.archivers.zip.ZipUtil.isDosTime(4036608000001L);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test22() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = org.apache.commons.compress.archivers.zip.ZipUtil.longToBig(-2147483648L);
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test23() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = org.apache.commons.compress.archivers.zip.ZipUtil.longToBig(163L);
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-93)), bigInteger0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (163)), bigInteger0.shortValue());
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.toLong(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(163L, long0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-93)), bigInteger0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (163)), bigInteger0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test24() throws java.lang.Throwable {
        int int0 = org.apache.commons.compress.archivers.zip.ZipUtil.signedByteToUnsignedInt(((byte) (83)));
        org.junit.jupiter.api.Assertions.assertEquals(83, int0);
    }

// ZipUtil_ESTest.test25:170 expected: <1392409281320> but was: <312770432000>
//    @org.junit.jupiter.api.Test
//    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
//    public void test25() throws java.lang.Throwable {
//        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.dosToJavaTime(3344L);
//        org.junit.jupiter.api.Assertions.assertEquals(1392409281320L, long0);
//    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test26() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.compress.archivers.zip.ZipUtil.isDosTime(-2903L);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }
}