/* This file was automatically generated by EvoSuite
Sun Apr 13 11:34:04 GMT 2025
 */
package org.apache.commons.numbers.fraction;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.math.BigInteger;
import org.apache.commons.numbers.fraction.BigFraction;
import java.math.RoundingMode;
import java.util.concurrent.TimeUnit;
import java.math.BigDecimal;
public class BigFraction_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test000() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-532.61341);
        float float0 = bigFraction0.floatValue();
        org.junit.jupiter.api.Assertions.assertEquals(-532.6134F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test001() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        bigFraction0.hashCode();
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test002() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-3489, 8);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.negate();
        boolean boolean0 = bigFraction0.equals(bigFraction1);
        org.junit.jupiter.api.Assertions.assertFalse(bigFraction1.equals(((java.lang.Object) (bigFraction0))));
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-76)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test003() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(((double) (2147483630)), -2130836488);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.of(-584L, -584L);
        int int0 = bigFraction0.compareTo(bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test004() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-2, -2);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.negate();
        int int0 = bigFraction1.compareTo(bigFraction1);
        org.junit.jupiter.api.Assertions.assertFalse(bigFraction1.equals(((java.lang.Object) (bigFraction0))));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-1)), bigFraction1.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test005() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.abs();
        org.junit.jupiter.api.Assertions.assertSame(bigFraction1, bigFraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test008() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(((double) (2147483648L)), 8);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test009() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(0.0, 0.0, 2416);
        bigFraction0.ZERO.subtract(131072L);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test010() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-717);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.subtract(-2052L);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1335)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test011() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        int int0 = bigFraction0.signum();
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test012() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-3489, 8);
        int int0 = bigFraction0.signum();
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-436)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test013() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1, 31);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.subtract(((long) (31)));
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.reciprocal();
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertFalse(bigFraction2.equals(((java.lang.Object) (bigFraction0))));
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-31)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test014() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(9007199254740990L, 9007199254740990L);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.negate();
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.reciprocal();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-1)), bigFraction2.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test015() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(3);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.pow(27);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-69)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test016() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.parse("-608077 / 1260");
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (30)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test017() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.parse("1 / 1333735776850284124449081472843776");
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test018() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.parse("1");
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test019() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.parse("1618607308 / 972079");
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1665)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test020() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[7];
        byteArray0[5] = ((byte) (-65));
        java.math.BigInteger bigInteger0 = new java.math.BigInteger(byteArray0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-16640)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test021() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-717);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.add(2006);
        java.math.BigInteger bigInteger0 = bigFraction1.getNumerator();
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-42)), bigFraction2.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-717)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test022() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(9007199254740990L, ((long) (2)));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-1)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test023() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(2847, ((int) ((byte) (2))));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-113)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test024() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-482.6007938, -2753);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.one();
        bigFraction1.negate();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-482)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test025() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(((double) (9007199254740990L)));
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.negate();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (2)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test026() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.of(-1735L);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction0.multiply(bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (57)), bigFraction2.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test027() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1581);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-23)), bigFraction1.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (45)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test028() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-947.0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-9470)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test029() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(2.6768168348567656E-8, 2.6768168348567656E-8, 971);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(971);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.multiply(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (9710)), bigFraction2.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test030() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1, 31);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(-371L);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-11)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test031() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(3);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(3);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (9)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test032() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1.0);
        long long0 = bigFraction0.longValue();
        org.junit.jupiter.api.Assertions.assertEquals(1L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test033() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-24);
        long long0 = bigFraction0.longValue();
        org.junit.jupiter.api.Assertions.assertEquals(-24L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test034() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(14L, -1793L);
        bigFraction0.ONE.isOne();
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test035() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        int int0 = bigFraction0.ONE.intValue();
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test036() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-728L);
        int int0 = bigFraction0.intValue();
        org.junit.jupiter.api.Assertions.assertEquals(-728, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test037() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1, 31);
        long long0 = bigFraction0.getNumeratorAsLong();
        org.junit.jupiter.api.Assertions.assertEquals(1L, long0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test038() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-3489, 8);
        long long0 = bigFraction0.getNumeratorAsLong();
        org.junit.jupiter.api.Assertions.assertEquals(-3489L, long0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (76)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test039() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        int int0 = bigFraction0.ZERO.getNumeratorAsInt();
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test040() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-482.6007938, -2753);
        int int0 = bigFraction0.getNumeratorAsInt();
        org.junit.jupiter.api.Assertions.assertEquals(-608077, int0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (30)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test041() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1, 31);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.subtract(((long) (31)));
        java.math.BigInteger bigInteger0 = bigFraction1.getNumerator();
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-31)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test042() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        java.math.BigInteger bigInteger0 = bigFraction0.getNumerator();
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test043() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1, 31);
        java.math.BigInteger bigInteger0 = bigFraction0.getNumerator();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigInteger0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test044() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1665.0985238854048);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.pow(38);
        long long0 = bigFraction1.getDenominatorAsLong();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1665)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-12450)), bigFraction1.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test045() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-440.3);
        int int0 = bigFraction0.getDenominatorAsInt();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-440)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test046() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-2, -2);
        int int0 = bigFraction0.getDenominatorAsInt();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test047() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-440.3);
        bigFraction0.getDenominator();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-440)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test048() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(14L, -1793L);
        java.math.BigInteger bigInteger0 = bigFraction0.getDenominator();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-1793)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test049() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-1.0, ((double) (1581)), 1581);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-1)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test050() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(0.0);
        double double0 = bigFraction0.doubleValue();
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test051() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-440.3);
        double double0 = bigFraction0.doubleValue();
        org.junit.jupiter.api.Assertions.assertEquals(-440.3, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test052() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(995);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.of(-1, 995);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction0.divide(bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-73)), bigFraction2.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test053() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-440.3);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.divide(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-440)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test054() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(0.0, 0.0, 2416);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ONE.multiply(bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.divide(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigFraction2.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (10)), bigFraction1.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test055() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-717);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.divide(((long) (-717)));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigFraction1.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-717)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test056() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        byte[] byteArray0 = new byte[4];
        byteArray0[2] = ((byte) (-124));
        java.math.BigInteger bigInteger0 = new java.math.BigInteger(byteArray0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.add(bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.divide(-1);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (31744)), bigFraction2.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test057() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1665.0985238854048, -1908874353);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.divide(-1);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.divide(1665L);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-127)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-1)), bigFraction2.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test058() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-3489, 8);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.negate();
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.divide(-277);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-1)), bigFraction2.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-76)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test059() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-390.0);
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.UP;
        java.math.BigDecimal bigDecimal0 = bigFraction0.bigDecimalValue(roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-390)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test060() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.UNNECESSARY;
        java.math.BigDecimal bigDecimal0 = bigFraction0.bigDecimalValue(roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test061() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(416L);
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.FLOOR;
        java.math.BigDecimal bigDecimal0 = bigFraction0.bigDecimalValue(roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (416)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test062() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(14L, -1793L);
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.UP;
        java.math.BigDecimal bigDecimal0 = bigFraction0.ONE.bigDecimalValue(-3788, roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test063() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-440.3);
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.DOWN;
        java.math.BigDecimal bigDecimal0 = bigFraction0.bigDecimalValue(1923, roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-440)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test064() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-3489, 8);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.negate();
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.CEILING;
        java.math.BigDecimal bigDecimal0 = bigFraction1.bigDecimalValue(64, roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (436)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test065() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(-1);
        java.math.BigDecimal bigDecimal0 = bigFraction1.bigDecimalValue();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-1)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test066() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(5.626783149637049E-6);
        java.math.BigDecimal bigDecimal0 = bigFraction0.bigDecimalValue();
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigDecimal0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test067() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(971);
        java.math.BigDecimal bigDecimal0 = bigFraction0.bigDecimalValue();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (971)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test068() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-9223372036854775808L);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.add(bigFraction0);
        org.junit.jupiter.api.Assertions.assertFalse(bigFraction2.equals(((java.lang.Object) (bigFraction1))));
        org.junit.jupiter.api.Assertions.assertNotSame(bigFraction2, bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction2.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test069() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0, bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test070() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(2710L);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-105)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test071() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-3065L, 131072L);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(((long) (-572)));
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-572)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test072() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(((long) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test073() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-4468.328376025);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ONE.add(((long) ((byte) (64))));
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-4468)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (65)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test074() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-390.0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(-1);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-391)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test075() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-440.3);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ONE.divide(652L);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.add(0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-440)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertSame(bigFraction2, bigFraction1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test076() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        byte[] byteArray0 = new byte[4];
        byteArray0[2] = ((byte) (-124));
        java.math.BigInteger bigInteger0 = new java.math.BigInteger(byteArray0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.add(bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.abs();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-31744)), bigFraction2.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test095() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1581);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.subtract(1581);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.divide(bigInteger0);
        org.junit.jupiter.api.Assertions.assertSame(bigFraction2, bigFraction1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test096() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1581);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.divide(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (158)), bigFraction1.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1581)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test097() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(2.6768168348567656E-8, 2.6768168348567656E-8, 971);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(971);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.subtract(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (961)), bigFraction2.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test098() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(2.6768168348567656E-8, 2.6768168348567656E-8, 971);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.subtract(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-10)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test099() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        boolean boolean0 = bigFraction0.isZero();
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test100() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1, 31);
        boolean boolean0 = bigFraction0.isZero();
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test101() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0, bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test102() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(2.6768168348567656E-8, 2.6768168348567656E-8, 971);
        int int0 = bigFraction0.signum();
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test103() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        byte[] byteArray0 = new byte[4];
        byteArray0[0] = ((byte) (3));
        byteArray0[3] = ((byte) (2));
        java.math.BigInteger bigInteger0 = new java.math.BigInteger(byteArray0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.add(bigInteger0);
        float float0 = bigFraction1.floatValue();
        org.junit.jupiter.api.Assertions.assertEquals(5.0331648E7F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test104() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        byte[] byteArray0 = new byte[19];
        byteArray0[0] = ((byte) (-50));
        java.math.BigInteger bigInteger0 = new java.math.BigInteger(byteArray0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.pow(((byte) (-124)));
        float float0 = bigFraction2.floatValue();
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test105() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1717986918);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.pow(2055);
        float float0 = bigFraction1.floatValue();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (26214)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Float.POSITIVE_INFINITY, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test106() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-485);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (27)), bigFraction0.byteValue());
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.pow(-2599);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.add(-2145779294);
        float float0 = bigFraction2.floatValue();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (418)), bigFraction2.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(-2.14577933E9F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test107() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-2147483646);
        float float0 = bigFraction0.floatValue();
        org.junit.jupiter.api.Assertions.assertEquals(-2.14748365E9F, float0, 0.01F);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (2)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test108() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(1581);
        boolean boolean0 = bigFraction0.ONE.equals(bigFraction0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (45)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test109() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1.0);
        boolean boolean0 = bigFraction0.ONE.equals(bigFraction0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test110() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(-3489, 8);
        boolean boolean0 = bigFraction0.ONE.equals(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (76)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test111() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        boolean boolean0 = bigFraction0.equals(bigFraction0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test112() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1.0);
        java.lang.Object object0 = new java.lang.Object();
        boolean boolean0 = bigFraction0.ZERO.equals(object0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test113() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(0.0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.of(-2130303777);
        int int0 = bigFraction0.compareTo(bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-33)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test114() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        int int0 = bigFraction0.compareTo(bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test115() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0);
        java.lang.String string0 = bigFraction0.toString();
        org.junit.jupiter.api.Assertions.assertEquals("1", string0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test116() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        java.lang.String string0 = bigFraction0.toString();
        org.junit.jupiter.api.Assertions.assertEquals("0", string0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test117() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(2.6768168348567656E-8);
        java.lang.String string0 = bigFraction0.toString();
        org.junit.jupiter.api.Assertions.assertEquals("120553113 / 4503599627370496", string0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test118() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.pow(-1);
        org.junit.jupiter.api.Assertions.assertNotSame(bigFraction1, bigFraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test120() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1.0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.pow(2146439152);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test121() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.pow(0);
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.subtract(bigInteger0);
        org.junit.jupiter.api.Assertions.assertNotSame(bigFraction2, bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertSame(bigFraction2, bigFraction1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test122() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.pow(1);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test123() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.divide(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test125() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-2373.0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.divide(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-2373)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test127() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.from(((double) (2147483634L)), 8);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction0.multiply(bigFraction1);
        org.junit.jupiter.api.Assertions.assertSame(bigFraction2, bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-14)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test128() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(0.0, 0.0, 2416);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(bigFraction0);
        org.junit.jupiter.api.Assertions.assertSame(bigFraction1, bigFraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test129() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        java.math.BigInteger bigInteger0 = java.math.BigInteger.TEN;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.multiply(bigInteger0);
        org.junit.jupiter.api.Assertions.assertSame(bigFraction1, bigFraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test130() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(((double) (2416)), ((double) (2416)), 5016);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (112)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test131() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(((long) (-2147483646)));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (2)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test132() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(9007199254740990L, 9007199254740990L);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ZERO.multiply(9007199254740990L);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test133() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(9007199254740990L, 9007199254740990L);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(0L);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test134() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(196633591);
        org.junit.jupiter.api.Assertions.assertSame(bigFraction1, bigFraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test135() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.multiply(0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test136() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(((double) (2147483630)), -2130836488);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.of(-584L, -584L);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.subtract(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (19)), bigFraction2.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test137() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0, bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.from(-879.185230917, -1);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction0.subtract(bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (879)), bigFraction2.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test138() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.subtract(bigFraction0);
        org.junit.jupiter.api.Assertions.assertSame(bigFraction1, bigFraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test139() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(((double) (2147483630)), -2130836488);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.subtract(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-18)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test140() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.subtract(1);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-1)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test141() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.of(-1);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction0.add(bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction2.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test142() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(2147483630);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.pow(-1736);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction0.add(bigFraction1);
        org.junit.jupiter.api.Assertions.assertNotSame(bigFraction2, bigFraction0);
        org.junit.jupiter.api.Assertions.assertFalse(bigFraction2.equals(((java.lang.Object) (bigFraction0))));
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-18)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-18)), bigFraction2.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test143() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = org.apache.commons.numbers.fraction.BigFraction.of(2147483629);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction0.add(bigFraction1);
        org.junit.jupiter.api.Assertions.assertSame(bigFraction2, bigFraction1);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-19)), bigFraction2.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test144() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test145() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(2.6768168348567656E-8, 2.6768168348567656E-8, 971);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.add(971);
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.pow(-43);
        boolean boolean0 = bigFraction0.ONE.equals(bigFraction2);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-53)), bigFraction1.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction2.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test146() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1.0);
        bigFraction0.abs();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test147() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-440.3);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.abs();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (440)), bigFraction1.shortValue());
        org.junit.jupiter.api.Assertions.assertNotSame(bigFraction1, bigFraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test148() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0, bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.subtract(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test149() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(0L, ((long) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test150() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(((long) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test154() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(302.874, -1842);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (46)), bigFraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test156() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(0.0010317822243450792, -2145469127);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test159() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        int int0 = bigFraction0.compareTo(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test160() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(2);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.ONE.reciprocal();
        org.apache.commons.numbers.fraction.BigFraction bigFraction2 = bigFraction1.subtract(bigFraction0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-1)), bigFraction2.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test161() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1.0);
        java.math.BigInteger bigInteger0 = bigFraction0.getDenominator();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigInteger0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test162() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(bigInteger0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.negate();
        org.junit.jupiter.api.Assertions.assertTrue(bigFraction1.equals(((java.lang.Object) (bigFraction0))));
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test163() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        bigFraction0.hashCode();
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test164() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(-482.6007938, -1601);
        boolean boolean0 = bigFraction0.isOne();
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (30)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test165() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.subtract(-1102);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1103)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test166() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        int int0 = bigFraction0.getNumeratorAsInt();
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test167() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ZERO;
        long long0 = bigFraction0.ZERO.longValue();
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test168() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(0);
        long long0 = bigFraction0.getNumeratorAsLong();
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test169() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(0.0);
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.divide(-2130303777);
        org.junit.jupiter.api.Assertions.assertSame(bigFraction1, bigFraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test170() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        org.apache.commons.numbers.fraction.BigFraction bigFraction1 = bigFraction0.zero();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigFraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test171() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1.0);
        java.math.BigDecimal bigDecimal0 = bigFraction0.bigDecimalValue();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigDecimal0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test172() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        int int0 = bigFraction0.getDenominatorAsInt();
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test173() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.ONE;
        double double0 = bigFraction0.ONE.doubleValue();
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test174() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.from(1.0);
        bigFraction0.ZERO.getDenominatorAsLong();
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigFraction0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigFraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test175() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.BigFraction bigFraction0 = org.apache.commons.numbers.fraction.BigFraction.of(0, 0);
        int int0 = bigFraction0.intValue();
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }
}