/* This file was automatically generated by EvoSuite
Thu Apr 03 21:38:59 GMT 2025
 */
package org.apache.commons.math4.core.jdkmath;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
import org.apache.commons.math4.core.jdkmath.JdkMath;
public class JdkMath_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test000() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.addExact(((long) (0)), ((long) (-1198)));
        org.junit.jupiter.api.Assertions.assertEquals(-1198L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test001() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.toRadians(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test002() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.toRadians(-142);
        org.junit.jupiter.api.Assertions.assertEquals(-2.478367537831948, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test003() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.toIntExact(0L);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test004() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.toIntExact(1L);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test005() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.toDegrees(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test006() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.toDegrees(1923.0);
        org.junit.jupiter.api.Assertions.assertEquals(110179.7840036573, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test007() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.tanh(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test008() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.tanh(-260.6785650113);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test009() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.tan(0.0F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test010() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.tan(573.285695314689);
        org.junit.jupiter.api.Assertions.assertEquals(18.175413227179195, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test011() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.subtractExact(((long) (-142)), -1535L);
        org.junit.jupiter.api.Assertions.assertEquals(1393L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test012() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.subtractExact(-1535L, 0L);
        org.junit.jupiter.api.Assertions.assertEquals(-1535L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test013() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.subtractExact(-53, -2113);
        org.junit.jupiter.api.Assertions.assertEquals(2060, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test014() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.subtractExact(1, 1746);
        org.junit.jupiter.api.Assertions.assertEquals(-1745, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test015() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.sqrt(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test016() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.sqrt(3.141592653589793);
        org.junit.jupiter.api.Assertions.assertEquals(1.7724538509055159, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test017() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.sinh(0.0F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test018() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.sinh(-1943.4143565);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test019() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.sin(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test020() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.sin(-420.8162333);
        org.junit.jupiter.api.Assertions.assertEquals(0.1565358487971272, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test021() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.signum(4558.734F);
        org.junit.jupiter.api.Assertions.assertEquals(1.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test022() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.signum(-1.0F);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test023() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.signum(5427.5143944);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test024() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.signum(-1.0);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test025() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.scalb(0.0F, 2330);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test026() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.scalb(-1.0F, -64);
        org.junit.jupiter.api.Assertions.assertEquals(-5.421011E-20F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test027() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.scalb(0.0, 1022);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test028() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.scalb(757.998165634217, 1198);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test029() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.round(1.4E-45F);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test030() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.round(((float) (1023)));
        org.junit.jupiter.api.Assertions.assertEquals(1023, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test031() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.round(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test032() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.round(((double) (-931)));
        org.junit.jupiter.api.Assertions.assertEquals(-931L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test033() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.rint(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test034() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.rint(-2945.52);
        org.junit.jupiter.api.Assertions.assertEquals(-2946.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test035() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.pow(0.0, 1.2207031E-4F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test036() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.pow(-574.401, -1L);
        org.junit.jupiter.api.Assertions.assertEquals(-0.0017409440443174717, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test037() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextUp(-1.4E-45F);
        org.junit.jupiter.api.Assertions.assertEquals(-0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test038() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextUp(-1.0F);
        org.junit.jupiter.api.Assertions.assertEquals(-0.99999994F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test039() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextUp(-4.9E-324);
        org.junit.jupiter.api.Assertions.assertEquals(-0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test040() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextUp(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(4.9E-324, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test041() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextDown(1.4E-45F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test042() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextDown(272.99783F);
        org.junit.jupiter.api.Assertions.assertEquals(272.9978F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test043() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextDown(2307.83);
        org.junit.jupiter.api.Assertions.assertEquals(2307.8299999999995, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test044() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextDown(((double) (-1063L)));
        org.junit.jupiter.api.Assertions.assertEquals(-1063.0000000000002, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test045() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextAfter(0.0F, ((double) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test046() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextAfter(-89.865F, 2.718281828459045);
        org.junit.jupiter.api.Assertions.assertEquals(-89.86499F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test047() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextAfter(0.0, ((double) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test048() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextAfter(1476.9662308767, 5427.5143944);
        org.junit.jupiter.api.Assertions.assertEquals(1476.9662308767001, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test049() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.negateExact(0L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test050() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.negateExact(1063L);
        org.junit.jupiter.api.Assertions.assertEquals(-1063L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test051() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.negateExact(0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test052() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.negateExact(-1198);
        org.junit.jupiter.api.Assertions.assertEquals(1198, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test053() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.multiplyExact(((long) (2)), 0L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test054() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.multiplyExact(((long) (-1794)), ((long) (1)));
        org.junit.jupiter.api.Assertions.assertEquals(-1794L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test055() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.multiplyExact(1, 0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test056() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.multiplyExact(249, 249);
        org.junit.jupiter.api.Assertions.assertEquals(62001, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test057() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.multiplyExact(-142, 675);
        org.junit.jupiter.api.Assertions.assertEquals(-95850, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test058() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(((long) (1023)), ((long) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test059() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(-4267615245585081135L, -2396L);
        org.junit.jupiter.api.Assertions.assertEquals(-4267615245585081135L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test060() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(764, 1041);
        org.junit.jupiter.api.Assertions.assertEquals(764, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test061() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(-127, 0);
        org.junit.jupiter.api.Assertions.assertEquals(-127, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test062() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(0.0F, 0.0F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test063() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(1754.9869F, 829.0F);
        org.junit.jupiter.api.Assertions.assertEquals(829.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test064() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(((double) (0.0F)), 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test065() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(1.0, 3.141592653589793);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test066() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(0L, 0L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test067() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(((long) (-127)), ((long) (1814)));
        org.junit.jupiter.api.Assertions.assertEquals(1814L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test068() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(0, -2362);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test069() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(-2082, -867);
        org.junit.jupiter.api.Assertions.assertEquals(-867, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test070() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(0.0F, -1651.5272F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test071() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(-3308.9966F, -3308.9966F);
        org.junit.jupiter.api.Assertions.assertEquals(-3308.9966F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test072() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(0.0, 4.7613641572445654E170);
        org.junit.jupiter.api.Assertions.assertEquals(4.7613641572445654E170, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test073() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(-1.0, -1.0);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test074() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log1p(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test075() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log1p(-0.12502530217170715);
        org.junit.jupiter.api.Assertions.assertEquals(-0.13356030981028572, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test076() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log10(585.7536383113198);
        org.junit.jupiter.api.Assertions.assertEquals(2.767714994825334, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test077() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log10(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test078() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log(5427.5143944);
        org.junit.jupiter.api.Assertions.assertEquals(8.599236553872375, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test079() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test080() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.incrementExact(2147483647L);
        org.junit.jupiter.api.Assertions.assertEquals(2147483648L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test081() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.incrementExact(-1725L);
        org.junit.jupiter.api.Assertions.assertEquals(-1724L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test082() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.incrementExact(1813);
        org.junit.jupiter.api.Assertions.assertEquals(1814, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test083() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.incrementExact(-1325);
        org.junit.jupiter.api.Assertions.assertEquals(-1324, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test084() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.hypot(1023, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(1023.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test085() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.getExponent(1.0F);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test086() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.getExponent(-80.0F);
        org.junit.jupiter.api.Assertions.assertEquals(6, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test087() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.getExponent(-1.0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test088() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.getExponent(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(-1023, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test089() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorMod(0L, -801L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test090() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorMod(-1097L, ((long) (1041)));
        org.junit.jupiter.api.Assertions.assertEquals(985L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test091() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorMod(4503599627370478L, -498L);
        org.junit.jupiter.api.Assertions.assertEquals(-74L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test092() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorMod(1223, 1223);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test093() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorMod(591, 10);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test094() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorMod(-236, -1399);
        org.junit.jupiter.api.Assertions.assertEquals(-236, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test095() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorDiv(0L, ((long) (1)));
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test096() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorDiv(((long) (-867)), ((long) (-867)));
        org.junit.jupiter.api.Assertions.assertEquals(1L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test097() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorDiv(2, 10);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test098() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorDiv(675, -142);
        org.junit.jupiter.api.Assertions.assertEquals(-5, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test099() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.floor(1.8836492887460383E270);
        org.junit.jupiter.api.Assertions.assertEquals(1.8836492887460383E270, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test100() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.floor(-2483.6339);
        org.junit.jupiter.api.Assertions.assertEquals(-2484.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test101() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.expm1(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test102() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.expm1(1.1921056801463227E-8);
        org.junit.jupiter.api.Assertions.assertEquals(1.1921056872519025E-8, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test103() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.exp(2.718281828459045);
        org.junit.jupiter.api.Assertions.assertEquals(15.154262241479262, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test104() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.decrementExact(774L);
        org.junit.jupiter.api.Assertions.assertEquals(773L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test105() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.decrementExact(0L);
        org.junit.jupiter.api.Assertions.assertEquals(-1L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test106() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.decrementExact(1);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test107() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.decrementExact(232);
        org.junit.jupiter.api.Assertions.assertEquals(231, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test108() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.decrementExact(-2113);
        org.junit.jupiter.api.Assertions.assertEquals(-2114, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test109() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.cos(2307.83);
        org.junit.jupiter.api.Assertions.assertEquals(-0.32422838809886767, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test110() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.copySign(0.0F, 511.52554F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test111() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.copySign(1204.68F, -1.0F);
        org.junit.jupiter.api.Assertions.assertEquals(-1204.68F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test112() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.copySign(0.0, -1452.3398189516804);
        org.junit.jupiter.api.Assertions.assertEquals(-0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test113() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.copySign(((double) (-1768)), ((double) (-1648L)));
        org.junit.jupiter.api.Assertions.assertEquals(-1768.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test114() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.ceil(1.2599210498948732);
        org.junit.jupiter.api.Assertions.assertEquals(2.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test115() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.ceil(-1088.21);
        org.junit.jupiter.api.Assertions.assertEquals(-1088.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test116() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.cbrt(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test117() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.cbrt(-1097L);
        org.junit.jupiter.api.Assertions.assertEquals(-10.313408245687409, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test118() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atanh(1);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test119() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atanh(-1.0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test120() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atan2(0, 27L);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test121() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atan2(-1657.976478450415, -1657.976478450415);
        org.junit.jupiter.api.Assertions.assertEquals(-2.356194490192345, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test122() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atan(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test123() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atan(-1916.9992442503);
        org.junit.jupiter.api.Assertions.assertEquals(-1.5702746782275883, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test124() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.asinh(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test125() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.asinh(-260.6785650113);
        org.junit.jupiter.api.Assertions.assertEquals(-6.256438956194929, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test126() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.asin(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test127() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.asin(1.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.5707963267948966, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test128() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.asin(-4.8465821804075345E-8);
        org.junit.jupiter.api.Assertions.assertEquals(-4.8465821804075365E-8, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test129() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.addExact(0L, 0L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test130() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.addExact(1073741796L, 1073741796L);
        org.junit.jupiter.api.Assertions.assertEquals(2147483592L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test131() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.addExact(0, 0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test132() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.addExact(0, -931);
        org.junit.jupiter.api.Assertions.assertEquals(-931, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test133() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.acosh(1.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test134() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.acosh(java.lang.Double.POSITIVE_INFINITY);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test135() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.acos(1.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test136() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(0L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test137() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(-4267615245585081135L);
        org.junit.jupiter.api.Assertions.assertEquals(4267615245585081135L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test138() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test139() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(-2030);
        org.junit.jupiter.api.Assertions.assertEquals(2030, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test140() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(0.0F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test141() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(694.806017147);
        org.junit.jupiter.api.Assertions.assertEquals(694.806017147, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test142() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.IEEEremainder(10, 2.356194490192345);
        org.junit.jupiter.api.Assertions.assertEquals(0.5752220392306207, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test143() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.IEEEremainder(-144.0F, 7.231299672196698E-12);
        org.junit.jupiter.api.Assertions.assertEquals(-3.410605131648481E-13, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test150() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.getExponent(((float) (0L)));
        org.junit.jupiter.api.Assertions.assertEquals(-127, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test151() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.signum(-0.0F);
        org.junit.jupiter.api.Assertions.assertEquals(-0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test152() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test153() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.random();
        org.junit.jupiter.api.Assertions.assertEquals(0.21142687464184484, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test154() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.negateExact(249);
        org.junit.jupiter.api.Assertions.assertEquals(-249, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test155() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.signum(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test156() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.getExponent(1705.9164218929684);
        org.junit.jupiter.api.Assertions.assertEquals(10, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test157() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atan2(1924.909F, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.5707963267948966, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test158() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log1p(1621.7600241446);
        org.junit.jupiter.api.Assertions.assertEquals(7.391883697151994, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test159() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(-9223372036854775808L);
        org.junit.jupiter.api.Assertions.assertEquals(-9223372036854775808L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test160() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextDown(4.9E-324);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test161() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.toRadians(4622.3044);
        org.junit.jupiter.api.Assertions.assertEquals(80.67443080942098, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test162() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextDown(-144.0F);
        org.junit.jupiter.api.Assertions.assertEquals(-144.00002F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test163() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.sinh(1.1705273659867328);
        org.junit.jupiter.api.Assertions.assertEquals(1.4567444742639433, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test164() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(2705.7112F);
        org.junit.jupiter.api.Assertions.assertEquals(2705.7112F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test165() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(-3560L, -3560L);
        org.junit.jupiter.api.Assertions.assertEquals(-3560L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test166() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.copySign(4767.7505F, 4767.7505F);
        org.junit.jupiter.api.Assertions.assertEquals(4767.7505F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test168() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atanh(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test169() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.ceil(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test170() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextAfter(626.2891F, -851.3876);
        org.junit.jupiter.api.Assertions.assertEquals(626.28906F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test171() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test172() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(883L, 883L);
        org.junit.jupiter.api.Assertions.assertEquals(883L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test175() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.acosh(-1.2296934902142301E22);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test176() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.ulp(-793.245F);
        org.junit.jupiter.api.Assertions.assertEquals(6.1035156E-5F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test178() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.cosh(-7.475571347653619E-8);
        org.junit.jupiter.api.Assertions.assertEquals(1.0000000000000029, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test179() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.atan(0.9166666666666666);
        org.junit.jupiter.api.Assertions.assertEquals(0.7419472680059175, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test180() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(-793.245F, -793.245F);
        org.junit.jupiter.api.Assertions.assertEquals(-793.245F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test181() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorDiv(2644281811660520851L, -3363L);
        org.junit.jupiter.api.Assertions.assertEquals(-786286592822041L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test182() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.scalb(java.lang.Float.POSITIVE_INFINITY, -1292);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Float.POSITIVE_INFINITY, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test183() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.floor(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test184() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.rint(1924.909F);
        org.junit.jupiter.api.Assertions.assertEquals(1925.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test185() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.expm1(-598.1554157353828);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test186() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.ulp(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(4.9E-324, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test187() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.incrementExact(-1L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test188() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.acos(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.5707963267948966, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test189() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log(1.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test190() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextUp(2790.854F);
        org.junit.jupiter.api.Assertions.assertEquals(2790.8542F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test191() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.sin(625.946166865);
        org.junit.jupiter.api.Assertions.assertEquals(-0.6955813794142736, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test192() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(25, 25);
        org.junit.jupiter.api.Assertions.assertEquals(25, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test193() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextUp(((double) (-4267615245585081135L)));
        org.junit.jupiter.api.Assertions.assertEquals(-4.2676152455850808E18, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test194() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(0, 250);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test195() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.hypot(0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test196() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.log10(1.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test197() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.tan(-25.182322084990325);
        org.junit.jupiter.api.Assertions.assertEquals(-0.04962152382791364, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test198() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.multiplyExact(913L, 913L);
        org.junit.jupiter.api.Assertions.assertEquals(833569L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test199() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.negateExact(-2644281811660520851L);
        org.junit.jupiter.api.Assertions.assertEquals(2644281811660520851L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test200() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.pow(0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test201() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.abs(java.lang.Integer.MIN_VALUE);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Integer.MIN_VALUE, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test202() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.copySign(4.230347870576539, 4.230347870576539);
        org.junit.jupiter.api.Assertions.assertEquals(4.230347870576539, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test203() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.floorDiv(232, 232);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test204() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.IEEEremainder(627.3822412897392, 627.3822412897392);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test205() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.subtractExact(-1L, -1L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test207() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.toIntExact(-496L);
        org.junit.jupiter.api.Assertions.assertEquals(-496, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test208() throws java.lang.Throwable {
        float float0 = org.apache.commons.math4.core.jdkmath.JdkMath.max(1924.909F, -1.4E-45F);
        org.junit.jupiter.api.Assertions.assertEquals(1924.909F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test209() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.addExact(232, 232);
        org.junit.jupiter.api.Assertions.assertEquals(464, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test210() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.toDegrees(-25.182322084990325);
        org.junit.jupiter.api.Assertions.assertEquals(-1442.840773809029, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test211() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.asinh(0.5015102846128487);
        org.junit.jupiter.api.Assertions.assertEquals(0.48256225648906537, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test212() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.nextAfter(-1642.3230133788775, -1642.3230133788775);
        org.junit.jupiter.api.Assertions.assertEquals(-1642.3230133788775, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test213() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.exp(-9223372036854775808L);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test214() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.cbrt(5427.5143944);
        org.junit.jupiter.api.Assertions.assertEquals(17.573853214665036, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test215() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.decrementExact(1L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test216() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.cos(2948.1);
        org.junit.jupiter.api.Assertions.assertEquals(0.2808747170375326, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test217() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.tanh(5427.5143944);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test218() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.min(-13.743957663254747, -13.743957663254747);
        org.junit.jupiter.api.Assertions.assertEquals(-13.743957663254747, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test219() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.core.jdkmath.JdkMath.scalb(-3657.82550466, 0);
        org.junit.jupiter.api.Assertions.assertEquals(-3657.82550466, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test220() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.subtractExact(249, 249);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test221() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.round(-80.29361F);
        org.junit.jupiter.api.Assertions.assertEquals(-80, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test222() throws java.lang.Throwable {
        long long0 = org.apache.commons.math4.core.jdkmath.JdkMath.round(2252.067);
        org.junit.jupiter.api.Assertions.assertEquals(2252L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test223() throws java.lang.Throwable {
        int int0 = org.apache.commons.math4.core.jdkmath.JdkMath.incrementExact(-1);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }
}