/* This file was automatically generated by EvoSuite
Mon Mar 17 08:13:35 GMT 2025
 */
package org.apache.commons.compress.archivers.zip;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.apache.commons.compress.archivers.zip.ZipUtil;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.math.BigInteger;
import java.util.concurrent.TimeUnit;
public class ZipUtil_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        byte byte0 = org.apache.commons.compress.archivers.zip.ZipUtil.unsignedIntToSignedByte(((byte) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), byte0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test01() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ZERO;
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.toLong(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[5];
        byteArray0[0] = ((byte) (-73));
        java.math.BigInteger bigInteger0 = new java.math.BigInteger(byteArray0);
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.toLong(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(5, byteArray0.length);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (-73)), ((byte) (0)), ((byte) (0)), ((byte) (0)), ((byte) (0)) }, byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(-313532612608L, long0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigInteger0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigInteger0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        int int0 = org.apache.commons.compress.archivers.zip.ZipUtil.signedByteToUnsignedInt(((byte) (1)));
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[0];
        byte[] byteArray1 = org.apache.commons.compress.archivers.zip.ZipUtil.reverse(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(0, byteArray0.length);
        org.junit.jupiter.api.Assertions.assertEquals(0, byteArray1.length);
        org.junit.jupiter.api.Assertions.assertNotNull(byteArray1);
        org.junit.jupiter.api.Assertions.assertSame(byteArray0, byteArray1);
        org.junit.jupiter.api.Assertions.assertSame(byteArray1, byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{  }, byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{  }, byteArray1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = org.apache.commons.compress.archivers.zip.ZipUtil.longToBig(-2147483648L);
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = org.apache.commons.compress.archivers.zip.ZipUtil.longToBig(-3533L);
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (51)), bigInteger0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-3533)), bigInteger0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test11() throws java.lang.Throwable {
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.adjustToLong(-3257);
        org.junit.jupiter.api.Assertions.assertEquals(4294964039L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        byte byte0 = org.apache.commons.compress.archivers.zip.ZipUtil.unsignedIntToSignedByte(165);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-91)), byte0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test14() throws java.lang.Throwable {
        byte byte0 = org.apache.commons.compress.archivers.zip.ZipUtil.unsignedIntToSignedByte(((byte) (14)));
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (14)), byte0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test16() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[5];
        byte[] byteArray1 = org.apache.commons.compress.archivers.zip.ZipUtil.reverse(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(5, byteArray0.length);
        org.junit.jupiter.api.Assertions.assertEquals(5, byteArray1.length);
        org.junit.jupiter.api.Assertions.assertNotNull(byteArray1);
        org.junit.jupiter.api.Assertions.assertSame(byteArray0, byteArray1);
        org.junit.jupiter.api.Assertions.assertSame(byteArray1, byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (0)), ((byte) (0)), ((byte) (0)), ((byte) (0)), ((byte) (0)) }, byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (0)), ((byte) (0)), ((byte) (0)), ((byte) (0)), ((byte) (0)) }, byteArray1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test17() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = org.apache.commons.compress.archivers.zip.ZipUtil.longToBig(183L);
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (183)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-73)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test19() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.compress.archivers.zip.ZipUtil.isDosTime(4036608000000L);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test20() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.compress.archivers.zip.ZipUtil.isDosTime(1392409281320L);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test21() throws java.lang.Throwable {
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.adjustToLong(0);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test22() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = org.apache.commons.compress.archivers.zip.ZipUtil.longToBig(-2116L);
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-2116)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-68)), bigInteger0.byteValue());
        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.toLong(bigInteger0);
        org.junit.jupiter.api.Assertions.assertEquals(4294965180L, long0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-2116)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-68)), bigInteger0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test23() throws java.lang.Throwable {
        int int0 = org.apache.commons.compress.archivers.zip.ZipUtil.signedByteToUnsignedInt(((byte) (0)));
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

// ZipUtil_ESTest.test24:172 expected: <1392409281320> but was: <4362702828000>
//    @org.junit.jupiter.api.Test
//    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
//    public void test24() throws java.lang.Throwable {
//        long long0 = org.apache.commons.compress.archivers.zip.ZipUtil.dosToJavaTime(-328L);
//        org.junit.jupiter.api.Assertions.assertEquals(1392409281320L, long0);
//    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test25() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.compress.archivers.zip.ZipUtil.isDosTime(-2116L);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }
}