/* This file was automatically generated by EvoSuite
Mon Mar 17 09:11:49 GMT 2025
 */
package org.apache.commons.imaging.common;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.math.BigInteger;
import org.apache.commons.imaging.common.AllocationRequestException;
import java.util.concurrent.TimeUnit;
public class AllocationRequestException_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test0() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ONE;
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(100, bigInteger0);
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException1 = new org.apache.commons.imaging.common.AllocationRequestException(-870, bigInteger0, allocationRequestException0);
        org.junit.jupiter.api.Assertions.assertNotNull(allocationRequestException1);
        org.junit.jupiter.api.Assertions.assertFalse(allocationRequestException1.equals(((java.lang.Object) (allocationRequestException0))));
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test1() throws java.lang.Throwable {
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(1578, 0);
        java.math.BigInteger bigInteger0 = allocationRequestException0.getRequest();
        org.junit.jupiter.api.Assertions.assertEquals(1578, allocationRequestException0.getLimit());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), bigInteger0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test2() throws java.lang.Throwable {
        java.math.BigInteger bigInteger0 = java.math.BigInteger.ONE;
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(100, bigInteger0);
        java.math.BigInteger bigInteger1 = allocationRequestException0.getRequest();
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigInteger0.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(100, allocationRequestException0.getLimit());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (1)), bigInteger1.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), bigInteger1.shortValue());
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger1);
        org.junit.jupiter.api.Assertions.assertSame(bigInteger0, bigInteger1);
        org.junit.jupiter.api.Assertions.assertSame(bigInteger1, bigInteger0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test3() throws java.lang.Throwable {
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(0, -2084);
        java.math.BigInteger bigInteger0 = allocationRequestException0.getRequest();
        org.junit.jupiter.api.Assertions.assertEquals(0, allocationRequestException0.getLimit());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-2084)), bigInteger0.shortValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-36)), bigInteger0.byteValue());
        org.junit.jupiter.api.Assertions.assertNotNull(bigInteger0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test4() throws java.lang.Throwable {
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(390, 0);
        int int0 = allocationRequestException0.getLimit();
        org.junit.jupiter.api.Assertions.assertEquals(390, allocationRequestException0.getLimit());
        org.junit.jupiter.api.Assertions.assertEquals(390, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test5() throws java.lang.Throwable {
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(-1288, 0);
        int int0 = allocationRequestException0.getLimit();
        org.junit.jupiter.api.Assertions.assertEquals(-1288, allocationRequestException0.getLimit());
        org.junit.jupiter.api.Assertions.assertEquals(-1288, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test6() throws java.lang.Throwable {
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(0, ((java.math.BigInteger) (null)));
        int int0 = allocationRequestException0.getLimit();
        org.junit.jupiter.api.Assertions.assertEquals(0, allocationRequestException0.getLimit());
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test7() throws java.lang.Throwable {
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(0, 1254);
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException1 = new org.apache.commons.imaging.common.AllocationRequestException(0, 0, allocationRequestException0);
        org.junit.jupiter.api.Assertions.assertNotNull(allocationRequestException1);
        org.junit.jupiter.api.Assertions.assertFalse(allocationRequestException1.equals(((java.lang.Object) (allocationRequestException0))));
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test8() throws java.lang.Throwable {
        org.apache.commons.imaging.common.AllocationRequestException allocationRequestException0 = new org.apache.commons.imaging.common.AllocationRequestException(0, ((java.math.BigInteger) (null)));
        java.math.BigInteger bigInteger0 = allocationRequestException0.getRequest();
        org.junit.jupiter.api.Assertions.assertEquals(0, allocationRequestException0.getLimit());
        org.junit.jupiter.api.Assertions.assertNull(bigInteger0);
    }
}