/* This file was automatically generated by EvoSuite
Thu Apr 03 22:23:05 GMT 2025
 */
package org.apache.commons.rng.core.util;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import org.apache.commons.rng.core.util.NumberFactory;
import java.util.concurrent.TimeUnit;
public class NumberFactory_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        byte[] byteArray0 = org.apache.commons.rng.core.util.NumberFactory.makeByteArray(-987L);
        int[] intArray0 = org.apache.commons.rng.core.util.NumberFactory.makeIntArray(byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new int[]{ -987, -1 }, intArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (37)), ((byte) (-4)), ((byte) (-1)), ((byte) (-1)), ((byte) (-1)), ((byte) (-1)), ((byte) (-1)), ((byte) (-1)) }, byteArray0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test01() throws java.lang.Throwable {
        byte[] byteArray0 = org.apache.commons.rng.core.util.NumberFactory.makeByteArray(-1);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (-1)), ((byte) (-1)), ((byte) (-1)), ((byte) (-1)) }, byteArray0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        long[] longArray0 = new long[2];
        longArray0[1] = -13894219205796L;
        byte[] byteArray0 = org.apache.commons.rng.core.util.NumberFactory.makeByteArray(longArray0);
        long[] longArray1 = org.apache.commons.rng.core.util.NumberFactory.makeLongArray(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(2, longArray1.length);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new long[]{ 0L, -13894219205796L }, longArray1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.makeInt(68719476752L);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        long long0 = org.apache.commons.rng.core.util.NumberFactory.makeLong(-1220, -4011);
        org.junit.jupiter.api.Assertions.assertEquals(-5235565137835L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        double double0 = org.apache.commons.rng.core.util.NumberFactory.makeDouble(-2912, 2888);
        org.junit.jupiter.api.Assertions.assertEquals(0.9999993145465951, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.rng.core.util.NumberFactory.makeBoolean(0L);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.rng.core.util.NumberFactory.makeBoolean(0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[0];
        long[] longArray0 = org.apache.commons.rng.core.util.NumberFactory.makeLongArray(byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new long[]{  }, longArray0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test09() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[8];
        byteArray0[0] = ((byte) (-108));
        long long0 = org.apache.commons.rng.core.util.NumberFactory.makeLong(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(148L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test10() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[8];
        byteArray0[7] = ((byte) (-53));
        long long0 = org.apache.commons.rng.core.util.NumberFactory.makeLong(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(-3819052484010180608L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test11() throws java.lang.Throwable {
        long long0 = org.apache.commons.rng.core.util.NumberFactory.makeLong(0, 0);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        long long0 = org.apache.commons.rng.core.util.NumberFactory.makeLong(16, 16);
        org.junit.jupiter.api.Assertions.assertEquals(68719476752L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test13() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[0];
        int[] intArray0 = org.apache.commons.rng.core.util.NumberFactory.makeIntArray(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(0, intArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test14() throws java.lang.Throwable {
        byte[] byteArray0 = org.apache.commons.rng.core.util.NumberFactory.makeByteArray(0);
        int int0 = org.apache.commons.rng.core.util.NumberFactory.makeInt(byteArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new byte[]{ ((byte) (0)), ((byte) (0)), ((byte) (0)), ((byte) (0)) }, byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test15() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[4];
        byteArray0[0] = ((byte) (1));
        int int0 = org.apache.commons.rng.core.util.NumberFactory.makeInt(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test16() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[4];
        byteArray0[3] = ((byte) (-119));
        int int0 = org.apache.commons.rng.core.util.NumberFactory.makeInt(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(-1996488704, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test17() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.makeInt(1617L);
        org.junit.jupiter.api.Assertions.assertEquals(1617, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test18() throws java.lang.Throwable {
        float float0 = org.apache.commons.rng.core.util.NumberFactory.makeFloat(0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test19() throws java.lang.Throwable {
        double double0 = org.apache.commons.rng.core.util.NumberFactory.makeDouble(0L);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test20() throws java.lang.Throwable {
        double double0 = org.apache.commons.rng.core.util.NumberFactory.makeDouble(27, 27);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test21() throws java.lang.Throwable {
        long[] longArray0 = new long[0];
        byte[] byteArray0 = org.apache.commons.rng.core.util.NumberFactory.makeByteArray(longArray0);
        org.junit.jupiter.api.Assertions.assertEquals(0, byteArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test22() throws java.lang.Throwable {
        int[] intArray0 = new int[0];
        byte[] byteArray0 = org.apache.commons.rng.core.util.NumberFactory.makeByteArray(intArray0);
        org.junit.jupiter.api.Assertions.assertEquals(0, byteArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test23() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.extractLo(0L);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test24() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.extractLo(1116L);
        org.junit.jupiter.api.Assertions.assertEquals(1116, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test25() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.extractHi(68719476752L);
        org.junit.jupiter.api.Assertions.assertEquals(16, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test26() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.extractHi(-3688L);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test34() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.extractHi(0L);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test35() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.extractLo(-3236L);
        org.junit.jupiter.api.Assertions.assertEquals(-3236, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test36() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.rng.core.util.NumberFactory.makeBoolean(-1995L);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test37() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.rng.core.util.NumberFactory.makeBoolean(((long) (81)));
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test38() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.rng.core.util.NumberFactory.makeBoolean(-2141648093);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test39() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.rng.core.util.NumberFactory.makeBoolean(3);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test40() throws java.lang.Throwable {
        double double0 = org.apache.commons.rng.core.util.NumberFactory.makeDouble(((long) (-20)));
        org.junit.jupiter.api.Assertions.assertEquals(0.9999999999999999, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test41() throws java.lang.Throwable {
        int int0 = org.apache.commons.rng.core.util.NumberFactory.makeInt(4294967295L);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test42() throws java.lang.Throwable {
        double double0 = org.apache.commons.rng.core.util.NumberFactory.makeDouble(1406, -2332);
        org.junit.jupiter.api.Assertions.assertEquals(3.2782553816002036E-7, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test45() throws java.lang.Throwable {
        int[] intArray0 = new int[3];
        byte[] byteArray0 = org.apache.commons.rng.core.util.NumberFactory.makeByteArray(intArray0);
        org.junit.jupiter.api.Assertions.assertEquals(12, byteArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test46() throws java.lang.Throwable {
        float float0 = org.apache.commons.rng.core.util.NumberFactory.makeFloat(-3236);
        org.junit.jupiter.api.Assertions.assertEquals(0.9999992F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test47() throws java.lang.Throwable {
        byte[] byteArray0 = new byte[8];
        long long0 = org.apache.commons.rng.core.util.NumberFactory.makeLong(byteArray0);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }
}