/* This file was automatically generated by EvoSuite
Fri Apr 04 14:40:19 GMT 2025
 */
package org.apache.commons.codec.binary;
import org.apache.commons.codec.binary.CharSequenceUtils;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.CharBuffer;
import java.util.concurrent.TimeUnit;
public class CharSequenceUtils_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test0() throws java.lang.Throwable {
        char[] charArray0 = new char[5];
        charArray0[1] = 'I';
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, true, 0, charBuffer0, 1, 74);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test1() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(((java.lang.CharSequence) (null)), true, -2980, ((java.lang.CharSequence) (null)), -2980, -2980);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test3() throws java.lang.Throwable {
        char[] charArray0 = new char[5];
        charArray0[1] = 'I';
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, false, 0, charBuffer0, 1, 1);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test4() throws java.lang.Throwable {
        char[] charArray0 = new char[5];
        charArray0[0] = 'I';
        charArray0[1] = 'I';
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, true, 0, charBuffer0, 1, 74);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test5() throws java.lang.Throwable {
        char[] charArray0 = new char[5];
        charArray0[1] = 'I';
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        java.nio.CharBuffer charBuffer1 = java.nio.CharBuffer.allocate(2790);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, true, 1, charBuffer1, 594, 2790);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test6() throws java.lang.Throwable {
        char[] charArray0 = new char[5];
        java.nio.CharBuffer charBuffer0 = java.nio.CharBuffer.wrap(charArray0);
        boolean boolean0 = org.apache.commons.codec.binary.CharSequenceUtils.regionMatches(charBuffer0, false, 1, charBuffer0, 0, 0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test8() throws java.lang.Throwable {
        org.apache.commons.codec.binary.CharSequenceUtils charSequenceUtils0 = new org.apache.commons.codec.binary.CharSequenceUtils();
    }
}