/* This file was automatically generated by EvoSuite
Mon Mar 17 16:11:22 GMT 2025
 */
package org.apache.commons.numbers.gamma;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
import org.apache.commons.numbers.gamma.Beta;
public class Beta_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test0() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.Beta.value(4534.56128, 1637.91);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test1() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.Beta.value(1.0, 1.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }
}