/* This file was automatically generated by EvoSuite
Mon Mar 17 16:04:13 GMT 2025
 */
package org.apache.commons.numbers.gamma;
import org.apache.commons.numbers.gamma.Policy;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import org.apache.commons.numbers.gamma.BoostGamma;
import java.util.concurrent.TimeUnit;
public class BoostGamma_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test000() throws java.lang.Throwable {
        double double0 = BoostGamma.Lanczos.lanczosSumExpGScaled(3113.1023);
        org.junit.jupiter.api.Assertions.assertEquals(0.006097162425862834, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test001() throws java.lang.Throwable {
        double double0 = BoostGamma.Lanczos.lanczosSum(2720.3299479391635);
        org.junit.jupiter.api.Assertions.assertEquals(2.523346492518384, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test002() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.upperGammaFraction(1042.509142636608, 2499.4647269, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(6.855568311586063E-4, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test003() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.upperGammaFraction(645.85423, 0.0, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(-0.0015483369985824819, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test004() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.uncheckedFactorial(0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test005() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaLower(2959.0, 0.0, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test006() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaLower(19, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test007() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaLower(0.054642130860422966, 3.307885441519386E107);
        org.junit.jupiter.api.Assertions.assertEquals(17.775167657135782, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test008() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma1pm1(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test009() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(-1223.30331);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test010() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(-0.0011295143874558028);
        org.junit.jupiter.api.Assertions.assertEquals(-885.9145555478791, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test011() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.sinpx(-1846.5506315356686);
        org.junit.jupiter.api.Assertions.assertEquals(1823.239825329351, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test012() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.sinpx(2211.69914750866);
        org.junit.jupiter.api.Assertions.assertEquals(-1792.7774213817377, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test013() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.regularisedGammaPrefix(1.0, -3.968365047179435E-5);
        org.junit.jupiter.api.Assertions.assertEquals(-3.968522529515628E-5, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test014() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = new org.apache.commons.numbers.gamma.Policy(1128.75763, 2875);
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lowerGammaSeries(541.4179966793687, 541.4179966793687, 1.0, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(2.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test015() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lowerGammaSeries(-1788.587556, 2279.0, 10.0, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test016() throws java.lang.Throwable {
        int[] intArray0 = new int[7];
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lgamma(2.0, intArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new int[]{ 1, 0, 0, 0, 0, 0, 0 }, intArray0);
        org.junit.jupiter.api.Assertions.assertEquals(7, intArray0.length);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test017() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lgamma(3865.441048541966);
        org.junit.jupiter.api.Assertions.assertEquals(28059.238060192503, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test018() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lgamma(-4027.35585116);
        org.junit.jupiter.api.Assertions.assertEquals(-29407.001091227838, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test019() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.incompleteTgammaLargeX(-1403.74909, 127.4, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test020() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.igammaTemmeLarge(266.3728391789249, 1.1240007277776077E21);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test021() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.igammaTemmeLarge(0.5622689000001628, 0.355977951457);
        org.junit.jupiter.api.Assertions.assertEquals(0.6501198931638202, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test022() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.igammaTemmeLarge(1.1102230246251565E-16, 1.1102230246251565E-16);
        org.junit.jupiter.api.Assertions.assertEquals(-8.816851514525786E147, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test023() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaQ(2.220446049250313E-16, 2782.5934776, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test024() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaQ(436, 436, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(0.4936312958917245, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test025() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaQ(6165.71143587843, 1.1240007277776077E21);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test026() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(1663.88069425, 10.0, ((org.apache.commons.numbers.gamma.Policy) (null)));
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test027() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(428.3592472882977, 0.9399557113647461);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test028() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.fullIgammaPrefix(1.0169288432614407E-13, 1399.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test029() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.fullIgammaPrefix(3021.705971173, 3021.705971173);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test030() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.fullIgammaPrefix(3.0, -2147030454);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NEGATIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test052() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(323.88258602351, 0.616203512528017);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test053() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(2591.598717756939, 5.61168275310625E-5);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test054() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(0.5772156649015329, 200.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test055() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(2.708782096718045E-4, 2.708782096718045E-4);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test056() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(2.2250738585072014E-308, 6759.031722334507);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test057() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(2833.2816290621777, java.lang.Double.POSITIVE_INFINITY);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test058() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(1650.2906906, -1198.81570475);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test059() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(java.lang.Double.POSITIVE_INFINITY, 422.0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test060() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(-1403.74909, -1403.74909);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test061() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(8162.037168722875, 6.02468004077673);
        org.junit.jupiter.api.Assertions.assertEquals(2.7030871597560122E-24, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test062() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(1.711224524281413E98, 538.52591);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test063() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(1.1102230246251565E-16, 1849.1888617742675);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test064() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(1.1102230246251565E-16, 1.1102230246251565E-16);
        org.junit.jupiter.api.Assertions.assertEquals(2.0000000000000004, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test065() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(422.0, -2.0);
        org.junit.jupiter.api.Assertions.assertEquals(176820.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test066() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(1.0, 20.0);
        org.junit.jupiter.api.Assertions.assertEquals(4.110317623312165E-19, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test067() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(2.0938631748758808E-4, 15.0);
        org.junit.jupiter.api.Assertions.assertEquals(5.4745406151303466E-8, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test068() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(5.574585761207606E196, 5.574585761207606E196);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test069() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(1.0, 5.109094217170944E19);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test070() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(java.lang.Double.NaN, 4.269068009004705E304);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test071() throws java.lang.Throwable {
        int[] intArray0 = new int[0];
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lgamma(6.797780477937208E-5, intArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new int[]{  }, intArray0);
        org.junit.jupiter.api.Assertions.assertEquals(0, intArray0.length);
        org.junit.jupiter.api.Assertions.assertEquals(9.596290072318387, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test072() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaQ(1380.49291706, 329.57);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test073() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(2720.3299479391635, 2704.25161863);
        org.junit.jupiter.api.Assertions.assertEquals(0.00733572940667137, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test074() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(39.95494378786165, 0.43931487008491427);
        org.junit.jupiter.api.Assertions.assertEquals(4.5279777404066334E-61, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test075() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(6.02468004077673, 2.5563239178728654E258, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test076() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.regularisedGammaPrefix(10.0, -339.758306410856);
        org.junit.jupiter.api.Assertions.assertEquals(2.028128433929301E167, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test077() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaLower(0.029015791000532906, 3.287218585534296E293, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(33.914734244163334, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test078() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(0.10526468069939171, java.lang.Double.POSITIVE_INFINITY);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test079() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(2.5, 2.5);
        org.junit.jupiter.api.Assertions.assertEquals(0.5528463292166206, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test080() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(695.6483694, 1508.0622360865998, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test081() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaQ(876.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test082() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(4618.827022081113, 4510.649322863661);
        org.junit.jupiter.api.Assertions.assertEquals(0.054863203983133615, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test083() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = new org.apache.commons.numbers.gamma.Policy(0.0033791670955125737, 57);
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(1.6239777734251093E-6, 57, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(3.033292916968374E-27, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test084() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(8.394987206720873E-4, 8.394987206720873E-4, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(0.9945522591486952, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test085() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(94.23257516391041, 0.018557330651423107);
        org.junit.jupiter.api.Assertions.assertEquals(3.324572367682081E144, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test086() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(39.410064322011635, 39.410064322011635);
        org.junit.jupiter.api.Assertions.assertEquals(0.5211857077062877, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test087() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(0.01950490012512188, 0.5, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(0.559218923480006, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test088() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(2.5066282746310002, 1170.1, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test089() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(0.5, 0.559218923480006);
        org.junit.jupiter.api.Assertions.assertEquals(0.7097449253116503, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test090() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(0.5, 1.4901161193847656E-8);
        org.junit.jupiter.api.Assertions.assertEquals(1.7722097102817287, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test091() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(4.0, 4.0);
        org.junit.jupiter.api.Assertions.assertEquals(2.600820722200253, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test092() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = new org.apache.commons.numbers.gamma.Policy(1.0, 1);
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaLower(1, 0.02558279715597587, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(0.024936618417624536, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test093() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(2.0, 2.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.5939941502901619, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test094() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaLower(3643.0, 1395.0, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test095() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(java.lang.Double.POSITIVE_INFINITY, java.lang.Double.POSITIVE_INFINITY);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test097() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(java.lang.Double.POSITIVE_INFINITY, -1139.36287);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test098() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(2279.0, java.lang.Double.NaN);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test099() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = org.apache.commons.numbers.gamma.Policy.getDefault();
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(java.lang.Double.NaN, 1.0, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test100() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(1.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test101() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(581.174165087, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test102() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(0.5622689000001628, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test103() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(java.lang.Double.POSITIVE_INFINITY, -1674.1);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test104() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(0.0, 2.6923694661863613E-4);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test105() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(-491.89, java.lang.Double.NaN);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test106() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(java.lang.Double.NaN, java.lang.Double.NaN);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test107() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma1pm1(2342.748);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test108() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma1pm1(-0.42278433509846713);
        org.junit.jupiter.api.Assertions.assertEquals(0.5438817418156617, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test109() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaPDerivative(5.52468004077673, 2279.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test110() throws java.lang.Throwable {
        int[] intArray0 = new int[2];
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lgamma(2.5338146255612166, intArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new int[]{ 1, 0 }, intArray0);
        org.junit.jupiter.api.Assertions.assertEquals(2, intArray0.length);
        org.junit.jupiter.api.Assertions.assertEquals(0.30873868356232465, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test111() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lgamma(2.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test112() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(java.lang.Double.POSITIVE_INFINITY, 695.6483694);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test113() throws java.lang.Throwable {
        int[] intArray0 = new int[2];
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lgamma(-22.643693341313973, intArray0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new int[]{ -1, 0 }, intArray0);
        org.junit.jupiter.api.Assertions.assertEquals(2, intArray0.length);
        org.junit.jupiter.api.Assertions.assertEquals(-49.23421911335352, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test114() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.regularisedGammaPrefix(-4.382036018453353E-9, 6802.7132);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test115() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lgamma(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test116() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.regularisedGammaPrefix(-2.0, 8.504785885678623E101);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test117() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.sinpx(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(-0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test118() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(49.36627253336, 8.018470256334202E-6);
        org.junit.jupiter.api.Assertions.assertEquals(5.15171257760124E61, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test119() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma1pm1(-4737.5622689);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test120() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaDeltaRatio(-0.79149064, 1.7211476576120028);
        org.junit.jupiter.api.Assertions.assertEquals(-5.306865993823567, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test121() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgamma(1508.0622360865998);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test122() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaRatio(1.503616514864999E300, 55.79861439940274);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test123() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaP(1.727788440360347E-309, 1.727788440360347E-309);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test125() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.gammaQ(192.59, 24.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test127() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.tgammaLower(-1881.695, 1838);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test128() throws java.lang.Throwable {
        double[] doubleArray0 = org.apache.commons.numbers.gamma.BoostGamma.getFactorials();
        org.junit.jupiter.api.Assertions.assertNotNull(doubleArray0);
        org.junit.jupiter.api.Assertions.assertEquals(171, doubleArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test129() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = new org.apache.commons.numbers.gamma.Policy(-1.0, 1838);
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.lowerGammaSeries(-978.9627457080566, 0.0, -1.0, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test130() throws java.lang.Throwable {
        org.apache.commons.numbers.gamma.Policy policy0 = new org.apache.commons.numbers.gamma.Policy(1128.75763, 2875);
        double double0 = org.apache.commons.numbers.gamma.BoostGamma.incompleteTgammaLargeX(30.0, 1128.75763, policy0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }
}