/* This file was automatically generated by EvoSuite
Thu Apr 03 21:17:25 GMT 2025
 */
package org.apache.commons.numbers.examples.jmh.core;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
public class ArithmeticPerformance_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-4L, -2607L);
        org.junit.jupiter.api.Assertions.assertEquals(1L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test01() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(0L, -1L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-250L, 1L);
        org.junit.jupiter.api.Assertions.assertEquals(-250L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-2334, -3457);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(0, -1846);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-1066, 20);
        org.junit.jupiter.api.Assertions.assertEquals(214748311, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-28, 1);
        org.junit.jupiter.api.Assertions.assertEquals(-28, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(0, 2417);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test09() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-1254L, -1887L);
        org.junit.jupiter.api.Assertions.assertEquals(633L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test10() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(((long) (0)), -1085L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test11() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-1061L, 1L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-1254L, ((long) (1)));
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test13() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-854, -3382);
        org.junit.jupiter.api.Assertions.assertEquals(2528, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test14() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(0, -1);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test15() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-1, 1);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test16() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(1, 692);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test18() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-263L, 1L);
        org.junit.jupiter.api.Assertions.assertEquals(-263L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test23() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-263L, -263L);
        org.junit.jupiter.api.Assertions.assertEquals(1L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test24() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(1688L, -1L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test25() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(((long) (-3382)), 420L);
        org.junit.jupiter.api.Assertions.assertEquals(43920819223117971L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test26() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-647L, 9223372036854775805L);
        org.junit.jupiter.api.Assertions.assertEquals(1L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test27() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(610L, 53L);
        org.junit.jupiter.api.Assertions.assertEquals(11L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test28() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-2309L, -1L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test29() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-1846, -79);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test30() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(78, -3017);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test31() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-1, 1);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test32() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-2144612679, 2147483646);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test33() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(657, 657);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test34() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.divideUnsigned(-2144612679, -2144612679);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test35() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-2607L, -1254L);
        org.junit.jupiter.api.Assertions.assertEquals(-2607L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test36() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(((long) (2147483646)), -2830L);
        org.junit.jupiter.api.Assertions.assertEquals(2147483646L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test37() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-1237L, 214L);
        org.junit.jupiter.api.Assertions.assertEquals(139L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test38() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-1061L, 20L);
        org.junit.jupiter.api.Assertions.assertEquals(15L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test39() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(94L, 1685L);
        org.junit.jupiter.api.Assertions.assertEquals(94L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test40() throws java.lang.Throwable {
        long long0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-1247L, -1247L);
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test41() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-3148, -209);
        org.junit.jupiter.api.Assertions.assertEquals(-3148, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test42() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-1, -1);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test43() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-854, 1);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test44() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-8, 1457);
        org.junit.jupiter.api.Assertions.assertEquals(833, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test45() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(-2145497075, 2146238729);
        org.junit.jupiter.api.Assertions.assertEquals(3231492, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test46() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance.remainderUnsigned(1, -3040);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test47() throws java.lang.Throwable {
        org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance arithmeticPerformance0 = new org.apache.commons.numbers.examples.jmh.core.ArithmeticPerformance();
    }
}