/* This file was automatically generated by EvoSuite
Thu Apr 03 21:30:15 GMT 2025
 */
package org.apache.commons.numbers.fraction;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
import org.apache.commons.numbers.fraction.Fraction;
public class Fraction_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test000() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-2332, -2332);
        fraction0.hashCode();
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.signum());
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.getDenominator());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test001() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(((double) (java.lang.Integer.MIN_VALUE)), java.lang.Integer.MIN_VALUE);
        fraction0.hashCode();
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Integer.MIN_VALUE, fraction0.intValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test002() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-2186, 1431655765);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.of(-2186);
        boolean boolean0 = fraction0.equals(fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction1.signum());
        org.junit.jupiter.api.Assertions.assertEquals(-1.526903361437587E-6, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-2186.0, fraction1.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertFalse(fraction1.equals(((java.lang.Object) (fraction0))));
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test003() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        boolean boolean0 = fraction0.equals(fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction1.signum());
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
        org.junit.jupiter.api.Assertions.assertEquals(0, fraction0.signum());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test004() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-713, 100);
        int int0 = fraction0.compareTo(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
        org.junit.jupiter.api.Assertions.assertEquals(-7.13F, fraction0.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test005() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.pow(java.lang.Integer.MIN_VALUE);
        org.junit.jupiter.api.Assertions.assertNotSame(fraction1, fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0F, fraction1.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test006() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-39.0, 0.0, 2205);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.divide(528);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.getDenominator());
        org.junit.jupiter.api.Assertions.assertEquals(-0.07386363F, fraction1.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test007() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-542, -3995);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.divide(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(0.13566958698372966, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), fraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test008() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-1931.2654947870953, 63);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.of(63, -1);
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction1.multiply(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction1.signum());
        org.junit.jupiter.api.Assertions.assertEquals(121669.71F, fraction2.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test009() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-713, 100);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.multiply(6443725);
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.subtract(fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(-183775037, fraction1.getNumerator());
        org.junit.jupiter.api.Assertions.assertEquals(45943752, fraction2.intValue());
        org.junit.jupiter.api.Assertions.assertEquals(-7.13F, fraction0.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test010() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(3113.1023);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.subtract(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(3113.102301790281, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(0, fraction1.getNumerator());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test011() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-306.0004);
        long long0 = fraction0.longValue();
        org.junit.jupiter.api.Assertions.assertEquals(-306.00040016006403, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-306L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test012() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(3113.1023);
        int int0 = fraction0.intValue();
        org.junit.jupiter.api.Assertions.assertEquals(3113.102301790281, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(3113, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test013() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-306.0004);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ONE.subtract(fraction0);
        boolean boolean0 = fraction1.isOne();
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
        org.junit.jupiter.api.Assertions.assertEquals(307.00040016006403, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test014() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-2332, 66);
        org.junit.jupiter.api.Assertions.assertEquals(-35.333333333333336, fraction0.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test015() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-1.0, -2606);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ZERO.negate();
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction1.abs();
        org.apache.commons.numbers.fraction.Fraction fraction3 = fraction0.ONE.subtract(fraction2);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction0.getNumerator());
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction3.signum());
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, fraction1.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test016() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(2485);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.of(2485, -1956);
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.ONE.subtract(fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(2.2704498977505114, fraction2.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-75)), fraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test017() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.subtract(-1);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction1.intValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test018() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-568, -568);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ONE.subtract(-568);
        boolean boolean0 = fraction0.equals(fraction1);
        org.junit.jupiter.api.Assertions.assertFalse(fraction1.equals(((java.lang.Object) (fraction0))));
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.signum());
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.getDenominator());
        org.junit.jupiter.api.Assertions.assertEquals(569, fraction1.intValue());
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test019() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-713, 100);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.subtract(6443725);
        org.junit.jupiter.api.Assertions.assertEquals(-6443732.13, fraction1.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction0.signum());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test020() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-2730);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ZERO.add(0);
        int int0 = fraction1.signum();
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
        org.junit.jupiter.api.Assertions.assertEquals(-2730.0F, fraction0.floatValue(), 0.01F);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction0.signum());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test021() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-1.0, 0.0, 1);
        int int0 = fraction0.signum();
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction0.getNumerator());
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test022() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-91.30761145182);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.reciprocal();
        org.junit.jupiter.api.Assertions.assertEquals(-0.010951989534251015, fraction1.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-91)), fraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test023() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-1);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.pow(-1);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction0.signum());
        org.junit.jupiter.api.Assertions.assertNotSame(fraction1, fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test024() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-621);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.pow(-1);
        fraction1.reciprocal();
        org.junit.jupiter.api.Assertions.assertEquals(-0.001610305958132045, fraction1.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-621L, fraction0.longValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test025() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.junit.jupiter.api.Assertions.assertTrue(fraction0.isZero());
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ZERO.subtract(java.lang.Integer.MIN_VALUE);
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction1.pow(1);
        org.junit.jupiter.api.Assertions.assertEquals(2.147483648E9, fraction2.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertSame(fraction2, fraction1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test026() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.parse("1");
        org.junit.jupiter.api.Assertions.assertTrue(fraction0.isOne());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test027() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.parse("1 / -313");
        org.junit.jupiter.api.Assertions.assertEquals(-0.003194888178913738, fraction0.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test028() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.parse("-39");
        org.junit.jupiter.api.Assertions.assertEquals(-39.0F, fraction0.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test029() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(1);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, fraction0.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test030() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-1);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.negate();
        org.junit.jupiter.api.Assertions.assertTrue(fraction1.isOne());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test031() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-306.0004);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ONE.multiply(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(-306.00040016006403, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test032() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(9, -607877445);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.multiply(-1);
        org.junit.jupiter.api.Assertions.assertEquals(-1.4805615957670546E-8, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(1.4805615957670546E-8, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test033() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-1);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.multiply(-1);
        org.junit.jupiter.api.Assertions.assertEquals(1.0F, fraction1.floatValue(), 0.01F);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0F, fraction0.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test034() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        long long0 = fraction0.longValue();
        org.junit.jupiter.api.Assertions.assertEquals(1L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test035() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(1.0E-5);
        int int0 = fraction0.intValue();
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, fraction0.floatValue(), 0.01F);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test036() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-1.0, java.lang.Integer.MAX_VALUE);
        int int0 = fraction0.intValue();
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.getDenominator());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test037() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        int int0 = fraction0.getNumerator();
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test038() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(1.0E-5);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ONE.reciprocal();
        int int0 = fraction1.getNumerator();
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
        org.junit.jupiter.api.Assertions.assertTrue(fraction1.isOne());
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, fraction0.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test039() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(((double) (1L)), 1862133);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (1)), fraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test040() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-1.0, 0.0, 1);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.of(1, -1288);
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.multiply(fraction1);
        org.apache.commons.numbers.fraction.Fraction fraction3 = org.apache.commons.numbers.fraction.Fraction.of(912411);
        org.apache.commons.numbers.fraction.Fraction fraction4 = fraction3.multiply(fraction2);
        org.junit.jupiter.api.Assertions.assertEquals(708.3936335403727, fraction4.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.getDenominator());
        org.junit.jupiter.api.Assertions.assertFalse(fraction2.equals(((java.lang.Object) (fraction1))));
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test041() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(1.0);
        org.junit.jupiter.api.Assertions.assertTrue(fraction0.isOne());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test042() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(1.0, 1.0, 1191);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ZERO.pow(122);
        float float0 = fraction1.floatValue();
        org.junit.jupiter.api.Assertions.assertTrue(fraction1.isZero());
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.intValue());
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test043() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(((double) (java.lang.Integer.MIN_VALUE)), 10);
        float float0 = fraction0.floatValue();
        org.junit.jupiter.api.Assertions.assertEquals(-2.147483648E9, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-2.14748365E9F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test044() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.negate();
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.add(fraction1);
        double double0 = fraction2.doubleValue();
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction1.getDenominator());
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(1.0F, fraction0.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test045() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-568, -568);
        double double0 = fraction0.doubleValue();
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.getDenominator());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test046() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction1.add(fraction0);
        org.apache.commons.numbers.fraction.Fraction fraction3 = org.apache.commons.numbers.fraction.Fraction.of(-1, 1080);
        org.junit.jupiter.api.Assertions.assertFalse(fraction3.isZero());
        org.apache.commons.numbers.fraction.Fraction fraction4 = fraction2.divide(fraction3);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction3.signum());
        org.junit.jupiter.api.Assertions.assertSame(fraction2, fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(-1080, fraction4.intValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test047() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(((double) (java.lang.Integer.MIN_VALUE)), 10);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction1.divide(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(-4.6566128730773926E-10, fraction2.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction0.signum());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test048() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(30.46054968246778);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ONE.divide(1);
        org.junit.jupiter.api.Assertions.assertEquals(30.460550458715595, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test049() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-1.0, 385);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.divide(-4);
        org.junit.jupiter.api.Assertions.assertEquals(0.25, fraction1.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-1)), fraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test050() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(-306.0004);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.ONE.add(fraction1);
        org.apache.commons.numbers.fraction.Fraction fraction3 = fraction2.divide(1);
        org.junit.jupiter.api.Assertions.assertEquals(-764695, fraction0.getNumerator());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (2)), fraction2.byteValue());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (2)), fraction3.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test051() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(2485);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.of(2485, -1956);
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.add(fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(2483.7295F, fraction2.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test052() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.from(-1898.3534241270631, java.lang.Integer.MIN_VALUE);
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction1.add(fraction0);
        org.junit.jupiter.api.Assertions.assertFalse(fraction2.isZero());
        org.junit.jupiter.api.Assertions.assertEquals(-607877445, fraction2.getNumerator());
        org.junit.jupiter.api.Assertions.assertSame(fraction2, fraction1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test053() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.add(0);
        org.junit.jupiter.api.Assertions.assertSame(fraction1, fraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test054() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(2485, -1956);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.add(221);
        org.junit.jupiter.api.Assertions.assertEquals(219.72955F, fraction1.floatValue(), 0.01F);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction0.signum());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test055() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(0.0, -864);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.add(java.lang.Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertEquals(2.147483647E9, fraction1.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertTrue(fraction0.isZero());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test056() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(63, java.lang.Integer.MIN_VALUE);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.abs();
        org.junit.jupiter.api.Assertions.assertEquals(-2.9336661E-8F, fraction0.floatValue(), 0.01F);
        org.junit.jupiter.api.Assertions.assertEquals(2.9336661100387573E-8, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test073() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        boolean boolean0 = fraction0.isZero();
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test074() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        boolean boolean0 = fraction0.isZero();
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test075() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(0, 0);
        org.junit.jupiter.api.Assertions.assertEquals(((short) (0)), fraction0.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test076() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(0.0, -3920.706806573, -1);
        org.junit.jupiter.api.Assertions.assertEquals(0, fraction0.signum());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test077() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        int int0 = fraction0.signum();
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test079() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(((double) (java.lang.Integer.MIN_VALUE)), 10);
        double double0 = fraction0.doubleValue();
        org.junit.jupiter.api.Assertions.assertEquals(-2.147483648E9, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test080() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(((double) (java.lang.Integer.MIN_VALUE)), java.lang.Integer.MIN_VALUE);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.of(java.lang.Integer.MIN_VALUE, 31);
        boolean boolean0 = fraction0.equals(fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(-6.927366606451613E7, fraction1.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction0.signum());
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test081() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(2147483601, 2147483601);
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.of(2147483601);
        boolean boolean0 = fraction1.equals(fraction0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, fraction0.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction1.signum());
        org.junit.jupiter.api.Assertions.assertFalse(fraction0.equals(((java.lang.Object) (fraction1))));
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.signum());
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (-47)), fraction1.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test082() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.negate();
        boolean boolean0 = fraction1.equals(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(0, fraction0.signum());
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction1.getDenominator());
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test083() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        boolean boolean0 = fraction1.equals(fraction0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
        org.junit.jupiter.api.Assertions.assertEquals(0, fraction0.signum());
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction1.signum());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test084() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        boolean boolean0 = fraction0.equals(fraction0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test085() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        java.lang.Object object0 = new java.lang.Object();
        boolean boolean0 = fraction0.equals(object0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test086() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        int int0 = fraction0.compareTo(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test087() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        int int0 = fraction1.compareTo(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test088() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        int int0 = fraction0.compareTo(fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test089() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        int int0 = fraction0.compareTo(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test090() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(3829.3047749171196);
        java.lang.String string0 = fraction0.toString();
        org.junit.jupiter.api.Assertions.assertEquals("2726465 / 712", string0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test091() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        java.lang.String string0 = fraction0.toString();
        org.junit.jupiter.api.Assertions.assertTrue(fraction0.isZero());
        org.junit.jupiter.api.Assertions.assertEquals("0", string0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test092() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        java.lang.String string0 = fraction0.toString();
        org.junit.jupiter.api.Assertions.assertEquals("1", string0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test094() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.pow(3355);
        org.junit.jupiter.api.Assertions.assertNotSame(fraction1, fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test096() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.pow(0);
        org.junit.jupiter.api.Assertions.assertSame(fraction1, fraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test097() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.junit.jupiter.api.Assertions.assertFalse(fraction1.isZero());
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.divide(fraction1);
        org.junit.jupiter.api.Assertions.assertSame(fraction2, fraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test099() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-1, -1);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.divide(-1);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.getNumerator());
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test101() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.divide(-2002);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test102() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction1.multiply(fraction0);
        org.junit.jupiter.api.Assertions.assertFalse(fraction0.isZero());
        org.junit.jupiter.api.Assertions.assertSame(fraction2, fraction1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test103() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.multiply(fraction0);
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction1.intValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test104() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.multiply(fraction0);
        org.junit.jupiter.api.Assertions.assertTrue(fraction1.isZero());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test105() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.multiply(1356);
        org.junit.jupiter.api.Assertions.assertSame(fraction1, fraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test106() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.multiply(-569);
        org.junit.jupiter.api.Assertions.assertFalse(fraction1.isZero());
        org.junit.jupiter.api.Assertions.assertEquals(((short) (-569)), fraction1.shortValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test107() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.multiply(0);
        org.junit.jupiter.api.Assertions.assertEquals(0, fraction1.getNumerator());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test108() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.subtract(fraction1);
        org.junit.jupiter.api.Assertions.assertEquals(-1, fraction2.getNumerator());
        org.junit.jupiter.api.Assertions.assertEquals(-1.0F, fraction2.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test109() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction2 = fraction0.add(fraction1);
        org.junit.jupiter.api.Assertions.assertSame(fraction2, fraction1);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test110() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.junit.jupiter.api.Assertions.assertTrue(fraction0.isZero());
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.ZERO.subtract(java.lang.Integer.MIN_VALUE);
        int int0 = fraction1.getDenominator();
        org.junit.jupiter.api.Assertions.assertFalse(fraction1.isZero());
        org.junit.jupiter.api.Assertions.assertEquals(2.147483648E9, fraction1.doubleValue(), 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test111() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.subtract(0);
        org.junit.jupiter.api.Assertions.assertSame(fraction1, fraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test113() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.add(-1174);
        org.junit.jupiter.api.Assertions.assertEquals(-1173, fraction1.intValue());
        org.junit.jupiter.api.Assertions.assertFalse(fraction1.isZero());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test114() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(0);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.add(0);
        org.junit.jupiter.api.Assertions.assertEquals(0, fraction1.getNumerator());
        org.junit.jupiter.api.Assertions.assertSame(fraction1, fraction0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test116() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-2147483624);
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.abs();
        org.junit.jupiter.api.Assertions.assertEquals(-2.14748365E9F, fraction0.floatValue(), 0.01F);
        org.junit.jupiter.api.Assertions.assertEquals(2147483624, fraction1.getNumerator());
        org.junit.jupiter.api.Assertions.assertEquals(2.147483624E9, fraction1.doubleValue(), 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test117() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        boolean boolean0 = fraction0.isOne();
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test118() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        boolean boolean0 = fraction0.isOne();
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test120() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.parse("0");
        org.junit.jupiter.api.Assertions.assertTrue(fraction0.isZero());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test126() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.from(3.7971403799019754E-11, 47);
        org.junit.jupiter.api.Assertions.assertEquals(((byte) (0)), fraction0.byteValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test128() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(10, -2404);
        org.junit.jupiter.api.Assertions.assertEquals(-0.0041597337F, fraction0.floatValue(), 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test130() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        int int0 = fraction0.getDenominator();
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test131() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.of(-2650);
        int int0 = fraction0.getNumerator();
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.getDenominator());
        org.junit.jupiter.api.Assertions.assertEquals(-2650, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test132() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.abs();
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction0.signum());
        org.junit.jupiter.api.Assertions.assertEquals(1, fraction1.intValue());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test133() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.zero();
        org.junit.jupiter.api.Assertions.assertEquals(0, fraction1.getNumerator());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test134() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        long long0 = fraction0.longValue();
        org.junit.jupiter.api.Assertions.assertEquals(0L, long0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test135() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        org.apache.commons.numbers.fraction.Fraction fraction1 = fraction0.one();
        org.junit.jupiter.api.Assertions.assertFalse(fraction1.isZero());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test136() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ZERO;
        fraction0.hashCode();
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test137() throws java.lang.Throwable {
        org.apache.commons.numbers.fraction.Fraction fraction0 = org.apache.commons.numbers.fraction.Fraction.ONE;
        float float0 = fraction0.floatValue();
        org.junit.jupiter.api.Assertions.assertEquals(1.0F, float0, 0.01F);
    }
}