/* This file was automatically generated by EvoSuite
Wed Mar 19 01:39:20 GMT 2025
 */
package org.apache.commons.lang3.math;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
import org.apache.commons.lang3.math.IEEE754rUtils;
public class IEEE754rUtils_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.min(0.0F, 0.0F, 995.0F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test01() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.min(4096.287F, 850.74F, 697.2F);
        org.junit.jupiter.api.Assertions.assertEquals(697.2F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.min(3202.81F, 3202.81F);
        org.junit.jupiter.api.Assertions.assertEquals(3202.81F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.min(-1.0F, -3242.5F);
        org.junit.jupiter.api.Assertions.assertEquals(-3242.5F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.min(37.595494885, 1746.8, ((double) (0.0F)));
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.min(1557.4889, 1557.4889, 1557.4889);
        org.junit.jupiter.api.Assertions.assertEquals(1557.4889, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.min(0.0, 1570.6515);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.min(212.86076562, 212.86076562);
        org.junit.jupiter.api.Assertions.assertEquals(212.86076562, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.max(0.0F, -3242.5F, 0.0F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test09() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.max(697.2F, -1.0F, -3294.89F);
        org.junit.jupiter.api.Assertions.assertEquals(697.2F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test10() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.max(-3242.5F, 74.898315F);
        org.junit.jupiter.api.Assertions.assertEquals(74.898315F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test11() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.max(-427.08F, -427.08F);
        org.junit.jupiter.api.Assertions.assertEquals(-427.08F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.max(0.0, 0.0, -2958.7956683);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test13() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.max(((double) (0.0F)), ((double) (-3242.5F)), ((double) (41.6F)));
        org.junit.jupiter.api.Assertions.assertEquals(41.599998474121094, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test14() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.max(-358.93116183, ((double) (0.0F)));
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test15() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.max(-358.93116183, -358.93116183);
        org.junit.jupiter.api.Assertions.assertEquals(-358.93116183, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test16() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.min(0.0F, 0.0F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test17() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.min(((double) (-427.08F)), 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(-427.0799865722656, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test18() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.max(0.0F, -732.32184F);
        org.junit.jupiter.api.Assertions.assertEquals(0.0F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test19() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.max(1093.39358351843, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(1093.39358351843, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test20() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.min(0.0F, 0.0F, -427.08F);
        org.junit.jupiter.api.Assertions.assertEquals(-427.08F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test21() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.min(-1.0, ((double) (0.0F)), 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test22() throws java.lang.Throwable {
        double double0 = org.apache.commons.lang3.math.IEEE754rUtils.max(-1179.172748, -1179.172748, -274.2113079);
        org.junit.jupiter.api.Assertions.assertEquals(-274.2113079, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test23() throws java.lang.Throwable {
        float float0 = org.apache.commons.lang3.math.IEEE754rUtils.max(-165.52022F, -165.52022F, -165.52022F);
        org.junit.jupiter.api.Assertions.assertEquals(-165.52022F, float0, 0.01F);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test24() throws java.lang.Throwable {
        org.apache.commons.lang3.math.IEEE754rUtils iEEE754rUtils0 = new org.apache.commons.lang3.math.IEEE754rUtils();
        org.junit.jupiter.api.Assertions.assertNotNull(iEEE754rUtils0);
    }
}