teralizer {
  project {
    root-path = "projects/commons-utils-es-default-60s"
    use-test-generation = true
    use-test-generalization = false
  }

  evosuite {
    search-budget = "60"
    assertion-strategy = "MUTATION"
    coverage-criterion = "LINE:BRANCH:EXCEPTION:WEAKMUTATION:OUTPUT:METHOD:METHODNOEXCEPTION:CBRANCH"
  }
}
