teralizer {
  project {
    root-path = "projects/commons-utils-es-weak-1s"
    use-test-generation = true
    use-test-generalization = false
  }

  evosuite {
    search-budget = "1"
    assertion-strategy = "UNIT"
    coverage-criterion = "LINE:BRANCH:EXCEPTION:OUTPUT:METHOD:METHODNOEXCEPTION:CBRANCH"
  }
}
