teralizer {
  project {
    root-path = "projects/eqbench-es-weak-60s"
    main-source-path = "projects/eqbench-es-weak-60s/src/main/code"
    test-source-path = "projects/eqbench-es-weak-60s/src/test/code"
    main-compiled-path = "projects/eqbench-es-weak-60s/target/classes"
    test-compiled-path = "projects/eqbench-es-weak-60s/target/test-classes"
    test-reports-path = "projects/eqbench-es-weak-60s/target/surefire-reports"
    coverage-reports-path = "projects/eqbench-es-weak-60s/target/site/jacoco"
    mutation-reports-path = "projects/eqbench-es-weak-60s/target/pit-reports"
    use-test-generation = true
    use-test-generalization = false
  }

  evosuite {
    search-budget = "60"
    assertion-strategy = "UNIT"
    coverage-criterion = "LINE:BRANCH:EXCEPTION:OUTPUT:METHOD:METHODNOEXCEPTION:CBRANCH"
  }
}
