/* This file was automatically generated by EvoSuite
Wed Mar 19 02:53:41 GMT 2025
 */
package org.apache.commons.geometry.euclidean.internal;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
import org.apache.commons.geometry.euclidean.internal.Vectors;
public class Vectors_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.normSq(4.149515568880993E180, 0.0, 7.187171792099953E180);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.POSITIVE_INFINITY, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test01() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.normSq(1.0, 1.0);
        org.junit.jupiter.api.Assertions.assertEquals(2.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.normSq(-1102.782849391046);
        org.junit.jupiter.api.Assertions.assertEquals(1216130.0129110345, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.norm(-1.0, 754.6204102, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(754.6210727844912, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.norm(0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.norm(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.linearCombination(6994660.067793724, 6994660.067793724, 2959.0, 7.888609052210118E-31, -3975.0, 2959.0);
        org.junit.jupiter.api.Assertions.assertEquals(4.89252577019631E13, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.linearCombination(-199.53676226, 0.0, -199.53676226, 1.0, 754.6204102, -1.0);
        org.junit.jupiter.api.Assertions.assertEquals(-954.1571724600001, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.linearCombination(4.149515568880993E180, 0.0, 4.149515568880993E180, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test09() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.linearCombination(-2267.270666905138, 828.95215880027, 0.0, 754.6210727844912);
        org.junit.jupiter.api.Assertions.assertEquals(-1879458.9139155422, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test10() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.checkedNorm(-3202.04);
        org.junit.jupiter.api.Assertions.assertEquals(-3202.04, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test11() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.geometry.euclidean.internal.Vectors.isRealNonZero(java.lang.Double.POSITIVE_INFINITY);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.geometry.euclidean.internal.Vectors.isRealNonZero(1430.450122136652);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test13() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.geometry.euclidean.internal.Vectors.isRealNonZero(0.0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test14() throws java.lang.Throwable {
        java.lang.IllegalArgumentException illegalArgumentException0 = org.apache.commons.geometry.euclidean.internal.Vectors.illegalNorm(7.888609052210118E-31);
        org.junit.jupiter.api.Assertions.assertNotNull(illegalArgumentException0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test15() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.checkedNorm(4502.110852385);
        org.junit.jupiter.api.Assertions.assertEquals(4502.110852385, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test17() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.linearCombination(-3104.52598, -3104.52598, -3104.52598, -3104.52598);
        org.junit.jupiter.api.Assertions.assertEquals(1.927616312098992E7, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test18() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.norm(0.0, 0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test19() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.normSq(0.0, 0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test20() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.normSq(0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test21() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.normSq(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test22() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.linearCombination(0.0, 0.0, -2438.5118112466, 0.0, 0.0, -2153.39514102234);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test23() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.norm(-1089.184976, -1089.184976);
        org.junit.jupiter.api.Assertions.assertEquals(1540.340164992214, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test24() throws java.lang.Throwable {
        double double0 = org.apache.commons.geometry.euclidean.internal.Vectors.norm(1.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }
}