plugins {
    id 'java'
    id 'jacoco'
    id 'info.solidsoft.pitest' version '1.15.0'
}

group = 'teralizer.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/junit/junit
    testImplementation 'junit:junit:4.13.2'
    // https://mvnrepository.com/artifact/org.junit.vintage/junit-vintage-engine
    testImplementation 'org.junit.vintage:junit-vintage-engine:5.11.0'
    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-launcher
    testImplementation 'org.junit.platform:junit-platform-launcher:1.11.0'
    // https://mvnrepository.com/artifact/net.jqwik/jqwik
    testImplementation("net.jqwik:jqwik:1.8.5")
    // https://mvnrepository.com/artifact/org.pitest/pitest-junit5-plugin
    implementation 'org.pitest:pitest-junit5-plugin:1.2.1'
}

test {
    useJUnitPlatform()
}

jacocoTestReport {
    reports {
        csv.required = true
        xml.required = true
    }
}

pitest {
    outputFormats = ['HTML', 'XML']
    exportLineCoverage = true
    verbose = true
    targetClasses = project.hasProperty('targetClasses') ? project.getProperty('targetClasses').split(',').toList() : ['*']
    targetTests = project.hasProperty('targetTests') ? project.getProperty('targetTests').split(',').toList() : ['*']
    mutators = project.hasProperty('mutators') ? project.getProperty('mutators').split(',') as Set : ['DEFAULTS'] as Set
}
