/* This file was automatically generated by EvoSuite
Wed Mar 19 02:18:36 GMT 2025
 */
package org.apache.commons.numbers.core;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.math.RoundingMode;
import java.util.concurrent.TimeUnit;
import org.apache.commons.numbers.core.Precision;
public class Precision_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(37.595494885);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.eqZero(37.595494885);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test01() throws java.lang.Throwable {
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.DOWN;
        double double0 = org.apache.commons.numbers.core.Precision.round(-1.0, 1, roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test02() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.core.Precision.round(696.0, 0);
        org.junit.jupiter.api.Assertions.assertEquals(696.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.core.Precision.round(-1571.0387, 1);
        org.junit.jupiter.api.Assertions.assertEquals(-1571.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.core.Precision.representableDelta(249.1904, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.core.Precision.representableDelta(0.0, -92.3329);
        org.junit.jupiter.api.Assertions.assertEquals(-92.3329, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(((float) (2162)), 1.0F, 2162);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(1.0F, 1979.687F);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(2117.2036F, -2245.4846F);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test09() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(1.0, ((double) (1)));
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.DOWN;
        double double0 = org.apache.commons.numbers.core.Precision.round(0.0, 2162, roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test13() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(886.529170768, ((double) (0)), 0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test14() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(((double) (-1.0F)), java.lang.Double.NaN, -1);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test15() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(((double) (2162)), ((double) (2162)), 2162);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test16() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(715.1, 1016.320377260457, 715.1);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test17() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(-97.137, 0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test18() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(365.6682, 365.6682, 365.6682);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test19() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(((float) (0)), ((float) (0)), 1645);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test20() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(2923.0F, 0.0F, 0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test21() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(3823.4746F, -1.0F, -1738);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test22() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.core.Precision.compareTo(-2085.0, java.lang.Double.NaN, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test23() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.core.Precision.compareTo(3448.479, -302.71, 3203.0);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test24() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.core.Precision.compareTo(0.0, 0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test25() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.core.Precision.compareTo(0.0, 4878.7956768495, 1.0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test26() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(439.6285774622);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        double double0 = precision_DoubleEquivalence0.signum(java.lang.Double.NaN);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test27() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(0.0);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        double double0 = precision_DoubleEquivalence0.signum(0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test28() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(85.2104);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.gte(1.0, 85.2104);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test29() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(1975.252F);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.gte(-1.0, 1975.252F);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test30() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(162.144539644494);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.gt(java.lang.Double.NaN, 392.606935);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test31() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(853.389809535);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.gt(1.0, 1545.8539324556);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test32() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(37.595494885);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.lte(0.0F, 37.595494885);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test33() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(0.0);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.lte(-1487.9145, -1516.082530269);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test36() throws java.lang.Throwable {
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.UP;
        double double0 = org.apache.commons.numbers.core.Precision.round(java.lang.Double.NaN, 1645, roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(java.lang.Double.NaN, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test37() throws java.lang.Throwable {
        java.math.RoundingMode roundingMode0 = java.math.RoundingMode.HALF_UP;
        double double0 = org.apache.commons.numbers.core.Precision.round(((double) (4271.9497F)), 0, roundingMode0);
        org.junit.jupiter.api.Assertions.assertEquals(4272.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test38() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(java.lang.Double.NaN, java.lang.Double.NaN, 0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test39() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(java.lang.Double.NaN, ((double) (1375)), 1375);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test40() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(886.529170768, 886.529170768, 0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test41() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(4155.085236);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.lt(0.0F, -0.0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test42() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(0.0, -1698.806011461478, 2144019964);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test43() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(1.0, 365.6682, ((double) (1039.944F)));
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test44() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(-1.0, 0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test45() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(0.0, 0.0, 0.0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test46() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsWithRelativeTolerance(-2125.16895247989, 226.77, 226.77);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test47() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsWithRelativeTolerance(0, 0.0, -983.2247504763);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test48() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsWithRelativeTolerance(727.959, java.lang.Double.NaN, java.lang.Double.NaN);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test49() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(1645);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.eq(1645, 1645);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test50() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(0.0, java.lang.Double.NaN);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test51() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(java.lang.Double.NaN, java.lang.Double.NaN);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test52() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(((double) (0)), ((double) (1645)));
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test53() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(-1237.1F, 0.0F, java.lang.Integer.MAX_VALUE);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test54() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(4271.9497F, -277.2098F, -277.2098F);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test55() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(0.0F, 996.0F, 996.0F);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test56() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(4270.0986F, 4270.0986F, 4270.0986F);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test57() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(526.338F, -2117.2036F, 4572.96F);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test58() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(2994.26F, ((float) (2162)), 526.338F);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test59() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(3352.4F, 3352.4F, 2117.2036F);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test60() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equalsIncludingNaN(0.0F, 0.0F);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test61() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.core.Precision.compareTo(((double) (0.0F)), 0.0, -1);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test62() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.core.Precision.compareTo(-1495.5454053103, -24.3877, -1);
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test63() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.core.Precision.compareTo(0.0, 0.0, 0);
        org.junit.jupiter.api.Assertions.assertEquals(0, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test64() throws java.lang.Throwable {
        int int0 = org.apache.commons.numbers.core.Precision.compareTo(((double) (-619)), -793.245333045262, -619);
        org.junit.jupiter.api.Assertions.assertEquals(1, int0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test65() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(853.389809535);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        double double0 = precision_DoubleEquivalence0.signum(1993.19455);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test66() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(471.71);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.lt(-2058.0, 0.0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test67() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(852.4728213368605);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        boolean boolean0 = precision_DoubleEquivalence0.eq(java.lang.Double.NaN, java.lang.Double.NaN);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test68() throws java.lang.Throwable {
        org.apache.commons.numbers.core.Precision.DoubleEquivalence precision_DoubleEquivalence0 = org.apache.commons.numbers.core.Precision.doubleEquivalenceOfEpsilon(853.389809535);
        org.junit.jupiter.api.Assertions.assertNotNull(precision_DoubleEquivalence0);
        double double0 = precision_DoubleEquivalence0.signum(853.389809535);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test69() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.core.Precision.representableDelta(2923.0F, 1858.9671);
        org.junit.jupiter.api.Assertions.assertEquals(1858.9670999999998, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test70() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(((double) (-1.0F)), ((double) (0.0F)));
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test71() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.numbers.core.Precision.equals(((float) (2162)), ((float) (2162)));
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test72() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.core.Precision.round(0.0, 0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }
}