/* This file was automatically generated by EvoSuite
Mon Mar 17 09:01:50 GMT 2025
 */
package org.apache.commons.math4.legacy.special;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import org.apache.commons.math4.legacy.special.BesselJ;
import java.util.concurrent.TimeUnit;
public class BesselJ_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test00() throws java.lang.Throwable {
        double[] doubleArray0 = new double[2];
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = new org.apache.commons.math4.legacy.special.BesselJ.BesselJResult(doubleArray0, -3565);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertArrayEquals(new double[]{ 0.0, 0.0 }, doubleArray0, 0.01);
        org.junit.jupiter.api.Assertions.assertEquals(-3565, besselJ_BesselJResult0.getnVals());
        org.junit.jupiter.api.Assertions.assertEquals(2, doubleArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test03() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(1.0E-4, 1.0E-4, 3109);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(54, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test04() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(1, 7.272995742657559E-235, 23);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(23, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test05() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(1, 0.0, 1);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(1, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test06() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(143, 0.0, 4133);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(610, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test07() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(686, 4.8381107817E-204, 686);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(686, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test08() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(2.324050160616117E-101, 8.9E-308, 600);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(3, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test09() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(0.0, 1.0E-4, 1);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(1, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test10() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(1.78E-307, 0.0, 143);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(1, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test11() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(3294198.0, 0.0, 372);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test12() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.legacy.special.BesselJ.value(120.0, 25.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.7377335293709727E-68, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test13() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.legacy.special.BesselJ.value(1, 1);
        org.junit.jupiter.api.Assertions.assertEquals(0.44005058574493355, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test14() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.legacy.special.BesselJ.value(1.0E-4, 6.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.15059998612443806, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test15() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(1.0, 0.0, 18);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(18, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test16() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.legacy.special.BesselJ.value(1, 143);
        org.junit.jupiter.api.Assertions.assertEquals(-0.049931489290181354, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test17() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.legacy.special.BesselJ.value(0.0, 34.4495808);
        org.junit.jupiter.api.Assertions.assertEquals(-0.08482031697533057, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test18() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.legacy.special.BesselJ.value(120.0, 120.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.0906850771040347, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test19() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.legacy.special.BesselJ.value(1693.6882, 6.283185307179586);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test21() throws java.lang.Throwable {
        double double0 = org.apache.commons.math4.legacy.special.BesselJ.value(1, 6.716441526213986E-8);
        org.junit.jupiter.api.Assertions.assertEquals(3.358220763106991E-8, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test22() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(0.0, 0.0, 582);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(582, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test23() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(8.9E-308, 8.9E-308, 1211);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(0, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test24() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(420.40674612061, -2294.7711, 82);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test25() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(-597.28271469, -597.28271469, 0);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test28() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(3003.2865644036797, 3003.2865644036797, 2);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, besselJ_BesselJResult0.getnVals());
        int int0 = besselJ_BesselJResult0.getnVals();
        org.junit.jupiter.api.Assertions.assertEquals(-1, int0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, besselJ_BesselJResult0.getnVals());
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test29() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ.BesselJResult besselJ_BesselJResult0 = org.apache.commons.math4.legacy.special.BesselJ.rjBesl(-1084.151, -1084.151, 687);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ_BesselJResult0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, besselJ_BesselJResult0.getnVals());
        double[] doubleArray0 = besselJ_BesselJResult0.getVals();
        org.junit.jupiter.api.Assertions.assertNotNull(doubleArray0);
        org.junit.jupiter.api.Assertions.assertEquals(-1, besselJ_BesselJResult0.getnVals());
        org.junit.jupiter.api.Assertions.assertEquals(687, doubleArray0.length);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test30() throws java.lang.Throwable {
        org.apache.commons.math4.legacy.special.BesselJ besselJ0 = new org.apache.commons.math4.legacy.special.BesselJ(0.0);
        org.junit.jupiter.api.Assertions.assertNotNull(besselJ0);
    }
}