/* This file was automatically generated by EvoSuite
Wed Mar 19 01:53:33 GMT 2025
 */
package org.apache.commons.numbers.gamma;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
import org.apache.commons.numbers.gamma.ErfDifference;
public class ErfDifference_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test0() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.ErfDifference.value(2333.492533, 3908.5304072);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test1() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.ErfDifference.value(-1390.1360756901, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test2() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.ErfDifference.value(0.0, 1.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.8427007929497149, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test3() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.ErfDifference.value(-0.47693627620446993, 0.0);
        org.junit.jupiter.api.Assertions.assertEquals(0.5, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test4() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.ErfDifference.value(0.0, -1523.42);
        org.junit.jupiter.api.Assertions.assertEquals(-1.0, double0, 0.01);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test5() throws java.lang.Throwable {
        double double0 = org.apache.commons.numbers.gamma.ErfDifference.value(-1.721393979585858, -1.721393979585858);
        org.junit.jupiter.api.Assertions.assertEquals(0.0, double0, 0.01);
    }
}