/* This file was automatically generated by EvoSuite
Sun Apr 13 10:43:07 GMT 2025
 */
package org.apache.commons.net.imap;
import org.apache.commons.net.imap.IMAPReply;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.TimeUnit;
public class IMAPReply_ESTest {
    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test0() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.net.imap.IMAPReply.isSuccess(-524);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test1() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.net.imap.IMAPReply.isContinuation(1);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test2() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.net.imap.IMAPReply.isSuccess(0);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test3() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.net.imap.IMAPReply.isSuccess(1253);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test4() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.net.imap.IMAPReply.isContinuation(3);
        org.junit.jupiter.api.Assertions.assertTrue(boolean0);
    }

    @org.junit.jupiter.api.Test
    @org.junit.jupiter.api.Timeout(value = 4000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
    public void test5() throws java.lang.Throwable {
        boolean boolean0 = org.apache.commons.net.imap.IMAPReply.isContinuation(4016);
        org.junit.jupiter.api.Assertions.assertFalse(boolean0);
    }
}