[project]
name = "teralizer-analysis"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "natsort>=8.4.0",
    "notebook>=7.4.4",
    "pandas>=2.3.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.41",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "teralizer-analysis",
]

[tool.uv.sources]
teralizer-analysis = { workspace = true }
